### ISSUE TITLE
Publish HTML to WebApp jobstep issue

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/Azure-MG-Sub-Governance-Reporting#102]
Hi,

I adopted the job step "Publish HTML to WebApp" as you can see below;

      jobs:
        AzGovViz:
          runs-on: ubuntu-latest
          environment: 'ssc-np'
          env:
            scope: '*****'
          steps:
      
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Internal Repository
              uses: actions/checkout@v3
            - name: Checkout JulianHayward/Azure-MG-Sub-Governance-Reporting
              uses: actions/checkout@v3
              with:
                repository: JulianHayward/Azure-MG-Sub-Governance-Reporting
                ref: v6_major_20220521_1
                clean: 'false' # Needed to add this otherwise the previous repo download is deleted first
      
            - name: Connect Azure
              uses: azure/login@v1
              with:
                creds: ${{secrets.CREDS}}
                enable-AzPSSession: true 
     
            - name: Check prerequisites
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  . .\$($env:ScriptDir)\$($env:ScriptPrereqFile) -OutputPath ${env:OutputPath}
                azPSVersion: "latest"
      
            - name: Run AzGovViz
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  . .\$($env:ScriptDir)\$($env:ScriptFile) -ManagementGroupId ${env:ManagementGroupId} -ScriptPath ${env:ScriptDir} -OutputPath ${env:OutputPath} -DoAzureConsumption -AzureConsumptionPeriod 28 -DoTranscript -ChangeTrackingDays 28
                azPSVersion: "latest"
            
            - name: Publish HTML to WebApp
              if: env.WebAppPublish == 'true'
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  --> Import-Module -Name AzAPICall <--
                  $azAPICallConf = initAzAPICall -DebugAZAPICall $true
                  $currentTask = "AzAPICall - Check if WebApp ($($env:WebAppName)) has Authentication enabled"
                  $uri = "$($azAPICallConf['azAPIEndpointUrls'].ARM)/subscriptions/$($env:WebAppSubscriptionId)/resourceGroups/$($env:WebAppResourceGroup)/providers/Microsoft.Web/sites/$($env:WebAppName)/config/authsettings/list?api-version=2021-02-01"
                  $method = 'POST'
                  $request = AzAPICall -AzAPICallConfiguration $azAPICallConf -uri $uri -method $method -currentTask $currentTask -listenOn 'Content'
                  $authStatus = $request.properties.enabled
                  Write-Host "WebApp ($($env:WebAppName)) has Authentication enabled: $authStatus"
                  if ($authStatus) {..........

If I leave out the "Import-Module -Name AzAPICall" then I received the error in the screenshot below.  Not sure if this is an intermittent error, but adding the import-module surely fixed it for me.

![image](https://user-images.githubusercontent.com/84451910/170294234-c50049dd-f61b-4529-98ac-33360dea27ad.png)

**Comment by wayneme75** [comment]
@MarcelHeek , I had a similar issue initially.. realized I had not updated both the pwsh files to the latest, the prerequisite and azgovviz . ps1 files.

**Comment by MarcelHeek** [comment]
@wayneme75  I checkout the repo in the workflow, so I use the ones from the public repo (v6_major_20220521_1), so that is not a workaround for me. The import-module does however....

**Comment by JulianHayward** [comment]
that´s strange/interesting, cannot reproduce. The module should be installed at the 'run AzGovViz' step and therefore loaded at the 'publish' step..

**Comment by MarcelHeek** [comment]
Will see if I can reproduce in the near future
