### ISSUE TITLE
Feature Request: Highlighting Quota allocation and usage

### ISSUE THREAD

**Issue by wayneme75** [JulianHayward/Azure-MG-Sub-Governance-Reporting#104]
Can we start to highlight quotas in the subs or within the limits area. In the event that you are running hot and need more capacity will the region / dc allow for the request

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits

**Comment by JulianHayward** [comment]
backlogged :)
