### ISSUE TITLE
AzGovViz Pipeline Exited with Code '1'

### ISSUE THREAD

**Issue by jose-ceschiatti** [JulianHayward/Azure-MG-Sub-Governance-Reporting#106]
Pipeline failed with bellow error when trying to run on a large tenant and I've verified microsoft.insights is registered on subscription:

!Please report at aka.ms/AzGovViz and provide the following dump
getDiagnosticSettingsSub for Subscription: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX - try #1; returned: (StatusCode: '404') <.code: ''> <.error.code: 'InvalidResourceType'> | <.message: ''> <.error.message: 'Resource type 'diagnosticSettings' of provider namespace 'microsoft.insights' was not found in global location for api version '2021-05-01-preview'.'> - (plain : @{error=}) - EXIT
Parameters:
accountType:ServicePrincipal
azAccountsVersion:n/a
azAPICallModuleVersion:1.1.12
codeRunPlatform:AzureDevOps
debugAzAPICall:False
debugWriteMethod:Host
DoAzureConsumption:False
DoNotIncludeResourceGroupsAndResourcesOnRBAC:False
DoNotIncludeResourceGroupsOnPolicy:False
DoNotShowRoleAssignmentsUserData:False
DoPSRule:False
gitHubRepository:aka.ms/AzGovViz
HierarchyMapOnly:False
LargeTenant:True
ManagementGroupsOnly:False
NoJsonExport:False
NoMDfCSecureScore:False
NoPolicyComplianceStates:True
NoResourceProvidersDetailed:True
NoResources:True
onAzureDevOps:True
onAzureDevOpsOrGitHubActions:True
onGitHubActions:False
PolicyAtScopeOnly:True
ProductVersion:v6_major_20220521_1
psVersion:7.2.3
RBACAtScopeOnly:True
subscriptionQuotaId:EnterpriseAgreement_2014-09-01
userType:n/a
writeMethod:Host
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:3665
Line |
3665 |              $batch.Group | ForEach-Object -Parallel {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

##[error]PowerShell exited with code '1'.

**Comment by JulianHayward** [comment]
please try the following for the failing Subscription

```PowerShell
$subscriptionId = '<subscriptionId>'

#https://docs.microsoft.com/en-us/rest/api/monitor/subscription-diagnostic-settings/list
$path = "/subscriptions/$subscriptionId/providers/Microsoft.Insights/diagnosticSettings?api-version=2021-05-01-preview"
$method = 'GET'
Invoke-AzRestMethod -Path $path -Method $method

#https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azdiagnosticsetting (api-version=2017-05-01-preview)
Get-AzDiagnosticSetting -SubscriptionId $subscriptionId
```

**Comment by jose-ceschiatti** [comment]
Looks like issues is with a specific subscription and not the code.
I've open a ticket with MS support as the above commands are also returning errors.
