### ISSUE TITLE
No HTML Output Created

### ISSUE THREAD

**Issue by ryanbal14** [JulianHayward/Azure-MG-Sub-Governance-Reporting#107]
The following lines is where the script terminates;

Exception: C:\Git\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:2949
Line |
2949 | $resourceTypesUnique.where( { $_.Name -like 'microsoft.*' }) …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Error - check the last console output for details

CSV files are outputted, but the HTML files are not. The script was also run with the -LargeTenant parameter, but HTML files were not created then either.

**Comment by ryanbal14** [comment]
The latest powershell version is being used. Also, the repo was just cloned earlier so the latest script is also being used. How would we go about outputting $resourceTypesUnique before 2949?

**Comment by JulianHayward** [comment]
just add:
`
$resourceTypesUnique
`
before line 2949

**Comment by ryanbal14** [comment]
I added that line in and received this message now:


Exception: C:\Git\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:2956
Line |
2956 | $microsoftResourceTypes | ForEach-Object -Parallel {
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Error - check the last console output for details

**Comment by JulianHayward** [comment]
ok, I don´t get it :). Let´s take this offline, please connect with me via LinkedIn.

**Comment by JulianHayward** [comment]
closing / issue was that Resource Provider Microsoft.Insights was not registered on a Subscription. Investigating how to improve error handling.
