### ISSUE TITLE
RequestConvertedFromJson error

### ISSUE THREAD

**Issue by ealdaon** [JulianHayward/Azure-MG-Sub-Governance-Reporting#108]
Hi,
i've cloned the repository and only changed the 2 neccesary variables (service account and management group), but i'm getting this error running the pipeline in devops (microsoft agents):

ConvertFrom-Json: /home/vsts/.local/share/powershell/Modules/AzAPICall/1.1.13/functions/AzAPICallFunctions.ps1:260
Line |
 260 |  … RequestConvertedFromJson = ($azAPIRequest.Content | ConvertFrom-Json)
     |                                                        ~~~~~~~~~~~~~~~~
     | Cannot convert the JSON string because it contains keys with
     | different casing. Please use the -AsHashTable switch instead.
     | The key that was attempted to be added to the existing key
     | 'StorageAccount' was 'storageAccount'.

##[error]PowerShell exited with code '1'.

![image](https://user-images.githubusercontent.com/79863609/171901270-fac179f5-4d5c-456f-b1fd-ae99d92616a5.png)

I've read the documentation and didn't see anything about this, could you help me?, thanks.

Regards.

**Comment by JulianHayward** [comment]
at what stage does the error happen, please share the output from before the error

**Comment by ealdaon** [comment]
Hi!,
let's see if it's enough with this screenshots, i've tried to figure out in which part of the pwsh script is located this error but didn't find anything:

![image](https://user-images.githubusercontent.com/89577258/171903093-ab9c1f24-cb93-49c4-bacd-54c594db3a5c.png)

![image](https://user-images.githubusercontent.com/89577258/171903379-62111999-26bb-41f9-8f11-b56ea98ebf67.png)

Thanks!

**Comment by JulianHayward** [comment]
ok, better. at line 476 please add:
`
$DebugAzAPICall = $true
`

**Comment by ealdaon** [comment]
![image](https://user-images.githubusercontent.com/89577258/171906533-4704c44a-5f43-4d68-af70-6feb8e0a83ff.png)

**Comment by JulianHayward** [comment]
I think we would need to take a closer look at your custom policy initiatives that are scoped at that Management Group.

**Comment by JulianHayward** [comment]
please try the following:

```PowerShell
foreach ($policySet in $resultHt.value) {
    $path = "$($policySet.id)?api-version=2021-06-01"
    $callPolicySet = Invoke-AzRestMethod -Path $path
    $resultPolicySet = $callPolicySet.Content | ConvertFrom-Json
}
```

Please share the policySetDefinition of those that are failing (maybe copy paste from the portal?)

**Comment by JulianHayward** [comment]
@ealdaon will you find some time to follow up?

**Comment by ealdaon** [comment]
Hi,
sorry, i didn't have a chance to test until now:
![image](https://user-images.githubusercontent.com/89577258/173006845-3d92ca9c-a24b-4119-a54c-134c2a2770a0.png)

**Comment by JulianHayward** [comment]
Please share the policySetDefinition of those that are failing (maybe copy paste from the portal?)

```PowerShell
foreach ($policySet in $resultHt.value) {
    Write-Host "this is the policySetId: $($policySet.id)"
    $path = "$($policySet.id)?api-version=2021-06-01"
    $callPolicySet = Invoke-AzRestMethod -Path $path
    $resultPolicySet = $callPolicySet.Content | ConvertFrom-Json
}
```

**Comment by ealdaon** [comment]
Hi,
![image](https://user-images.githubusercontent.com/89577258/174241635-e90024ce-0bf5-47ad-ae8f-78245d68e499.png)

With -AsHashTable:
![image](https://user-images.githubusercontent.com/89577258/174242249-8f30a655-6e5f-480e-8919-c60bcf656096.png)


From where is taking the "Storage" or "storage" value?, both of them am from inititives, in one of those initiatives there's only 1 policy definition which is built-in in fact:
![image](https://user-images.githubusercontent.com/89577258/174242826-f37dbb9d-2da9-499c-8c44-debaee118ea1.png)
![image](https://user-images.githubusercontent.com/89577258/174242863-b8443d53-cd17-4475-b36b-e91fae4d287c.png)

`{
  "properties": {
    "displayName": "Secure transfer to storage accounts should be enabled",
    "policyType": "BuiltIn",
    "mode": "Indexed",
    "description": "Audit requirement of Secure transfer in your storage account. Secure transfer is an option that forces your storage account to accept requests only from secure connections (HTTPS). Use of HTTPS ensures authentication between the server and the service and protects data in transit from network layer attacks such as man-in-the-middle, eavesdropping, and session-hijacking",
    "metadata": {
      "version": "2.0.0",
      "category": "Storage"
    },
    "parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "The effect determines what happens when the policy rule is evaluated to match"
        },
        "allowedValues": [
          "Audit",
          "Deny",
          "Disabled"
        ],
        "defaultValue": "Audit"
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
          },
          {
            "anyOf": [
              {
                "allOf": [
                  {
                    "value": "[requestContext().apiVersion]",
                    "less": "2019-04-01"
                  },
                  {
                    "field": "Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly",
                    "exists": "false"
                  }
                ]
              },
              {
                "field": "Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly",
                "equals": "false"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]"
      }
    }
  },
  "id": "/providers/Microsoft.Authorization/policyDefinitions/404c3081-a854-4457-ae30-26a93ef643f9",
  "type": "Microsoft.Authorization/policyDefinitions",
  "name": "404c3081-a854-4457-ae30-26a93ef643f9"
}`

Thanks!

**Comment by JulianHayward** [comment]
ok, please do the following for these two policySetDefinitionIds and share:

![image](https://user-images.githubusercontent.com/45695032/174262051-6900c1be-6d6a-49e9-82ea-76fcbda6a9c6.png)

![image](https://user-images.githubusercontent.com/45695032/174262120-fddf84b2-85d3-43ad-bd7c-3b3594167c76.png)


```PowerShell
$path = "<enter policySetDefinitionId>?api-version=2021-06-01"
$callPolicySet = Invoke-AzRestMethod -Path $path
$resultPolicySet = $callPolicySet.Content
$resultPolicySet
```

**Comment by ealdaon** [comment]
Hi,
here you go:
![image](https://user-images.githubusercontent.com/89577258/174653113-ae332a6a-c3a4-405c-803e-469cbe1bd76f.png)

Thanks!

**Comment by JulianHayward** [comment]
hi, but these are not the two failing policySet definitions. 

Please run for theses 2:
![image](https://user-images.githubusercontent.com/45695032/174667923-980dcc97-a808-47f8-b345-b3521735bbee.png)

**Comment by JulianHayward** [comment]
@ealdaon will you provide the output? Curious :)
