### ISSUE TITLE
404 - NotFound (running against root tenant id)

### ISSUE THREAD

**Issue by mfmalto** [JulianHayward/Azure-MG-Sub-Governance-Reporting#109]
we have everything under the root management group.  nothing else.  when i attempt to run the script (i'm a global admin), i get the following error:

Checking permissions for ManagementGroup '<tenant root id>' - try #1; returned: (StatusCode: '404') <.code: ''> <.error.code: 'NotFound'> | <.message: ''> <.error.message: ''/providers/Microsoft.Management/managementGroups/<tenant root id>' not found'> - (plain : @{error=}) - EXIT
Parameters:
accountType:User
azAccountsVersion:2.8.0
azAPICallModuleVersion:1.1.13
codeRunPlatform:Console
debugAzAPICall:False
debugWriteMethod:Host
DoAzureConsumption:False
DoNotIncludeResourceGroupsAndResourcesOnRBAC:False
DoNotIncludeResourceGroupsOnPolicy:False
DoNotShowRoleAssignmentsUserData:False
DoPSRule:True
gitHubRepository:aka.ms/AzGovViz
HierarchyMapOnly:False
LargeTenant:False
ManagementGroupsOnly:False
NoJsonExport:False
NoMDfCSecureScore:False
NoPolicyComplianceStates:False
NoResourceProvidersDetailed:False
NoResources:False
onAzureDevOps:False
onAzureDevOpsOrGitHubActions:False
onGitHubActions:False
PolicyAtScopeOnly:False
ProductVersion:v6_major_20220603_1
psVersion:7.2.4
RBACAtScopeOnly:False
subscriptionQuotaId:EnterpriseAgreement_<redacted>
userType:Member
writeMethod:Host
Exception:
Line |
 465 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
you need to have RBAC Role 'Reader' assigned at that Management Group.  
[setup Guide](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#azgovviz-setup-guide)

**Comment by JulianHayward** [comment]
please ping me on linkedIn?

**Comment by mfmalto** [comment]
issue is resolved.  no root tenant which caused this to not run.  created a root tenant and viola, success.  if you try to run this against the tenant, it will not work.  thanks julian.
