### ISSUE TITLE
Include CSS and secondary JS files

### ISSUE THREAD

**Issue by ChristopherGLewis** [JulianHayward/Azure-MG-Sub-Governance-Reporting#11]
Can you change the Could you include the CSS and secondary JS files in the code tree?  I'm trying to view an older run report and the changes you're making to the CSS are breaking old reports.

![image](https://user-images.githubusercontent.com/8505994/92140013-30754f00-edd6-11ea-8b3c-3ef2e9751b9f.png)

This would also allow for custom styles.

Another approach would be to version the CSS down to sub-version (azgovvisv30r3  vs azgovvisv3), but I'd still like to see secondary files includes.

**Comment by JulianHayward** [comment]
actually the css files are versioned. Wondering why from your screenshot azgovvizmain_xxx.css is not listed. Please check the head section in your html file. Note: azgovvizversion.css is not relevant to styling.

**Comment by JulianHayward** [comment]
no response; providing css/js added to backlog
