### ISSUE TITLE
Installing 'AzAPICall' module (Group) failed

### ISSUE THREAD

**Issue by piyushkhadgiazure** [JulianHayward/Azure-MG-Sub-Governance-Reporting#119]
While using AzGovViz Code with Azure DevOps, getting this error.

--------------------------------------------------------------------------------------------

 Line |
23291 |  …             throw "  Installing '$($module.ModuleName)' module ($($mo …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   Installing 'AzAPICall' module (Group) failed

##[error]PowerShell exited with code '1'.
![AzGov](https://user-images.githubusercontent.com/91533714/178251979-11e0eeb0-9dd8-4c0f-8f41-64f38f09105c.png)

**Comment by JulianHayward** [comment]
did you copy&paste the script content? Any other adjustments from your side?   
please try with the latest version 20220710_1

**Comment by piyushkhadgiazure** [comment]
No changes done. Following the setup file. Tried latest version still getting same error.

I used same PowerShell script in Azure Cloud shell, there it asked me to install API call and it works. But it is not working in DevOps pipeline.

**Comment by piyushkhadgiazure** [comment]
Thanks Julian for your assistance.
Appreciate it !
