### ISSUE TITLE
Unexpected token in AzGovViz.ps1

### ISSUE THREAD

**Issue by stefanstranger** [JulianHayward/Azure-MG-Sub-Governance-Reporting#12]
I cloned the repo and wanted to run the AzGovViz.ps1 script but it gives me the following error:

Unexpected token '}' in expression or statement. (linenumber 11232,13)

**Comment by JulianHayward** [comment]
fixed?, please try again.

**Comment by JulianHayward** [comment]
seems it worked out fine..
https://stefanstranger.github.io/2020/08/28/EnterpriseScalePolicyDrivenGovernance/
