### ISSUE TITLE
How to use this in already existing resource graph manager API for orphaned resources.

### ISSUE THREAD

**Issue by yashaswi90** [JulianHayward/Azure-MG-Sub-Governance-Reporting#120]
How to use that like if I have created a workbook for orphaned resources so how to incorporate this which will help in identifying the cost of orphaned resources in that query?

**Comment by yashaswi90** [comment]
> AzGovViz

@JulianHayward Could you please provide the example for the query if we want to use this AzGovViz what all the things that need to do in order to get the result for all the resources.

**Comment by JulianHayward** [comment]
all the information is available in this repository.  
[SetupGuide](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup.md)

**Comment by yashaswi90** [comment]
Thankyou @JulianHayward  for your kind help.
