### ISSUE TITLE
The screipt failes to write back to the folder

### ISSUE THREAD

**Issue by ctahok** [JulianHayward/Azure-MG-Sub-Governance-Reporting#122]
Hi there,

I am getting following error while the script is writing back the results to my output folder with following error:

To https://dev.azure.com/MyOrg/MyProjject1/_git/Enterprise%20Scale%20-%20Azure%20Platform  ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://dev.azure.com/MyOrg/MyProjject1/_git/Project1'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
##[error]PowerShell exited with code '1'.
Finishing: Push AzGovViz output to repository

If I completely delete my AzGovViz_output folder and re-run the pipeline it works fine but fails again on the next run. 
Please advise

**Comment by JulianHayward** [comment]
it sounds like there was a push against the repository after you launched the pipeline and before the pipeline push was initiated

**Comment by ctahok** [comment]
I removed the output folder, re-run, made sure everything is synced up and re-run again and the issue is gone.
