### ISSUE TITLE
Unable to create file wiki/JSON_..... Filename too long

### ISSUE THREAD

**Issue by Tsholofelom** [JulianHayward/Azure-MG-Sub-Governance-Reporting#123]
Hi Julian 
I am getting an error at the checkout stage error: unable to create file wiki/JSON_......  .json: Filename too long
What do I need to change please.

**Comment by JulianHayward** [comment]
read the fine manual :)
https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#known-issues

**Comment by JulianHayward** [comment]
hmm, that sounds odd. But you are using the default yaml? The worker is Ubuntu?

![image](https://user-images.githubusercontent.com/45695032/182613102-bb84ddd0-3d50-46cc-9fdb-2e5a1574fec2.png)

**Comment by Tsholofelom** [comment]
I am using an Azure Windows scaleset

**Comment by Tsholofelom** [comment]
Hi Julian 
I will use an Ubuntu image 
Thank you
