### ISSUE TITLE
Pipeline authorization issue

### ISSUE THREAD

**Issue by Tsholofelom** [JulianHayward/Azure-MG-Sub-Governance-Reporting#124]
Hi Julian 
This is not an issue with the script per se but perhaps you have come across it before.
I added the service connection and management group values in the variable file, however 
I am  getting an error:

"There was a resource authorization issue: "The pipeline is not valid. Job AzGovViz: Step AzurePowerShell1 input ConnectedServiceNameARM references service connection $(ServiceConnection) which could not be found. The service connection does not exist or has not been authorized for use. "  

I click on the authorize option that is part of the error and I get the message back that authorization was successful. I verified that my service connection has permissions to all pipelines.
I deleted and recreated the service connection.
Any suggestions please?
What am I over looking.
Thank you

**Comment by JulianHayward** [comment]
check the variables.yaml the variable name is 'ServiceConnection' and the value also is correct?  
![image](https://user-images.githubusercontent.com/45695032/182888306-86e0d857-8b02-48e6-aa67-c6989bd56075.png)

**Comment by Tsholofelom** [comment]
Hi Julian 
Error was caused because I was adding the name of the service connection in 35.
I changed the name to ServiceConnection, pipeline is now running.
Thank you
