### ISSUE TITLE
Issue with the diagnostic

### ISSUE THREAD

**Issue by zilberd** [JulianHayward/Azure-MG-Sub-Governance-Reporting#126]
The script is failing during the Checking Resource Types Diagnostics capability (1st party only)

!Please report at aka.ms/AzGovViz and provide the following dump
Checking if ResourceType 'microsoft.databricks/workspaces' is capable for Resource Diagnostics using 3 ResourceId: '/subscriptions/XXXXX-XXXXX-XXXX-XXXXX-XXXXXXXXXXXXXXXX/resourcegroups/databricks-course/providers/microsoft.databricks/workspaces/databricks' - try #1; returned: (StatusCode: '409') <.code: 'AuthorizationFailed'> <.error.code: ''> | <.message: 'Please register the subscription 'XXXXX-XXXXX-XXXX-XXXXX-XXXXXXXXXXXXXXXX' with Microsoft.Insights.'> <.error.message: ''> - (plain : @{code=AuthorizationFailed; message=Please register the subscription 'XXXXX-XXXXX-XXXX-XXXXX-XXXXXXXXXXXXXXXX' with Microsoft.Insights.}) - EXIT

**Comment by JulianHayward** [comment]
in this case three options: 
1. enable the provider for that subscription
2. use the parameter `-ExcludedResourceTypesDiagnosticsCapable`
3. go with option 1 and let´s arrange a troubleshooting session (as I cannot repro this issue (even if I unregister the insights provider)) - update the getResourceDiagnosticsCapability function to try resources from other subs / we´d also need to update the AzAPICall module.

**Comment by zilberd** [comment]
I went for the option 1, this came from a subscription that was provisionned by a user directly (I have no idea how).
So it wasn't following our normal subscriptions deployment (working under MCA)

let's close it and I'll re-open it if after deploy a "real" subscription.

I also have to understand how the user went betwen the cracks...
