### ISSUE TITLE
Issue Running Script 

### ISSUE THREAD

**Issue by clifpi** [JulianHayward/Azure-MG-Sub-Governance-Reporting#127]
Hi,
I am running the script point specifically the management group, it looks to run well but I get this error

!Please report at aka.ms/AzGovViz and provide the following dump
Caching built-in Role definitions - try #1; returned: (StatusCode: '404') <.code: ''> <.error.code: 'InvalidResourceType'> | <.message: ''> <.error.message: 'The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2022-04-01'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2018-01-01-preview,2018-07-01'.'> - (plain : @{error=}) - EXIT

Followed by this
Line |
1738 |      $arrayBuiltInCaching | ForEach-Object -parallel {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

Any thoughts? thank you for your time!

**Comment by JulianHayward** [comment]
hi, assuming you are not running in public cloud (AzureCloud) but some sovereign cloud.  
Please try the following: in the `azGovVizParallel.ps1` file replace `2022-04-01` (3 occurrences) with `2018-07-01`.

**Comment by clifpi** [comment]
sorry this is Azure government cloud.

**Comment by clifpi** [comment]
Did you still want mt to attempt your suggestion? How would I do this? thank you for your feedback.

**Comment by JulianHayward** [comment]
yes, just edit the file `AzGovVizParallel.ps1` and replace the string `2022-04-01` with `2018-07-01`. Then it should work in Azure Government. Seems that API version `2022-04-03` is not available in sovereign clouds, yet.

**Comment by clifpi** [comment]
Hi,
I replaced  $ProductVersion = 'v6_major_20220803_1', with $ProductVersion = 'v6_major_20180701_1',

I received the same error, did I modify the correct line? I did not see anything else referencing 2022
!Please report at aka.ms/AzGovViz and provide the following dump
Caching built-in Role definitions - try #1; returned: (StatusCode: '404') <.code: ''> <.error.code: 'InvalidResourceType'> | <.message: ''> <.error.message: 'The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2022-04-01'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2018-01-01-preview,2018-07-01'.'> - (plain : @{error=}) - EXIT

Exception: C:\temp\Azure-MG-Sub-Governance-Reporting-master\pwsh\AzGovVizParallel.ps1:1738
Line |
1738 |      $arrayBuiltInCaching | ForEach-Object -parallel {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
please ping me on LinkedIn ..

**Comment by clifpi** [comment]
unfortunately I do not have linkedin, I sent you an email to your MS email or if you have another way to contact you

**Comment by JulianHayward** [comment]
Fixed with release v6_major_20220817_1

* __Update: IMPORTANT Fix__ for custom Role definitions / missing DataActions and NotDataActions
  * Update [API reference](#api-reference) roleDefinitions use API version 2018-07-01 (API version 2022-04-01 not available in sovereign clouds)
* BugFix
