### ISSUE TITLE
Object reference not set to an instance of an object. $SubscriptionIdForDefinitionCaching

### ISSUE THREAD

**Issue by niklasfink** [JulianHayward/Azure-MG-Sub-Governance-Reporting#13]
Hello, I cannot seem to get the script running. The issue I'm having is the following error which stops the script:

```
Get-AzRoleDefinition: /mnt/c/code/Azure-MG-Sub-Governance-Reporting/pwsh/AzGovViz.ps1:10223
 Line |
10223 |  … finitions = Get-AzRoleDefinition -Scope "/subscriptions/$Subscription …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Object reference not set to an instance of an object.
```

Before that, I get the following output which already looks wrong to me due to the SubscriptionId:
OK Subscription context (QuotaId not 'AAD_*') for Definition Caching (**SubscriptionId: ;** QuotaId: EnterpriseAgreement_2014-09-01 EnterpriseAgreement_2014-09-01 _[...] many more_

I'm reader on Management Root Group level and executing the script after login via `Connect-AzAccount`. There are multiple lower management groups and multiple subscriptions. When I start the script, I also get `Access test passed: ManagementGroupId 'xxx' is accessible`.

I'm also wondering why I don't get any console output for `$checkContext.Subscription.Id` after doing `$checkContext = Get-AzContext -ErrorAction Stop`.

`Get-AzContext -ListAvailable` gives
```
Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
xx-ID1 - …                               email@mail.com                                                                               AzureCloud                                xx-ID1
```

**Comment by JulianHayward** [comment]
hello, I also just recently seen that -> get-Azcontext not showing a subscription. try the following: set context to a subscription (set-azcontext -subscription xxx) and then rerun the script?

**Comment by niklasfink** [comment]
Setting the context to a subscription worked.

**Comment by JulianHayward** [comment]
added to backlog. closing
