### ISSUE TITLE
Only first pipeline run is successful, scheduled ones fails

### ISSUE THREAD

**Issue by ctahok** [JulianHayward/Azure-MG-Sub-Governance-Reporting#130]
Hi there, 

I am not sure what is wrong here but my pipeline runs smoothly without any issues on the first run only. The scheduled one fails at Push AzGovViz output to repository struggling tthe o overwrite with following message:
`create mode 100644 AzGovViz_output/JSON_2a1c1XXXX/Tenant/2a1c1XXXX (Tenant Root Group)/mg-root-level (mg-root-level)/ra_User_f0ec1XXXXXXXXXXXX.json
To https://dev.azure.com/MyOrg/MyProject20-%20Azure%20Platform/_git/ES%20-%20Azure%20Platform
 ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://dev.azure.com/MyOrg/MyProject20-%20Azure%20Platform/_git/ES%20-%20Azure%20Platform'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
##[error]PowerShell exited with code '1'.
Finishing: Push AzGovViz output to repository`

Just to clarify I am not using VS or any other tool for source control, just ADO.

[https://i.imgur.com/TbORRjv.png](url)

Please help

**Comment by JulianHayward** [comment]
hello @ctahok 
it looks like that 'something' pushed to the repo after the pipeline kicked off and before the push back to repo step was reached :)

**Comment by ctahok** [comment]
> hello @ctahok it looks like that 'something' pushed to the repo after the pipeline kicked off and before the push back to repo step was reached :)

My output folder was created **/output** which is also part of the repo.
The only thing which updates it is the script itself by generating the new output files. If I delete **/output** and leave it for the next scheduled time it will work again.

**Comment by JulianHayward** [comment]
but the error message clearly indicating that the push is behind its remote. Can you please track the commit history? If still in doubt please ping me on LinkedIn :)

**Comment by ctahok** [comment]
Will do, thanks a lot Julian

**Comment by JulianHayward** [comment]
@ctahok any news on this one?

**Comment by ctahok** [comment]
Hi Julian,

I looked at it and the repo I placed the files contains multiple other
files and pipelines from different projects. You were right they might have
been updated. On the other hand I am not completely sure if it would be
affected if none of the files inside AzGovViz and AzGovViz _Output folders
were changed but other folders and files have changed.
So what I need to do is place it in its own repo and have its own pipeline
created. Please close this issue as it is clearly not a code issues but
git's one. Thanks again for the brilliant tool and amazing support.

Regards, Ilkin
