### ISSUE TITLE
Error on diagnosticsPolicyAnalysis

### ISSUE THREAD

**Issue by BevanSin** [JulianHayward/Azure-MG-Sub-Governance-Reporting#132]
When running against my tenant I get a stop error at:
processing TenantSummary Diagnostics Resource Diagnostics Policy Lifecycle
AzGovVizParallel.ps1: You cannot call a method on a null-valued expression.

I did some debugging and found on line 20464
if (($diagnosticsPolicyAnalysis.ResourceType).ToLower() -notcontains ( ($resourceTypeDiagnosticsCapable.ResourceType).ToLower() )) {

The diagnosticsPolicyAnalysis array object is empty so it crashes out.  I fixed it by changing to just checking if it was empty

if ($diagnosticsPolicyAnalysis.count -eq 0) {

but Im sure that breaks\misses something.  Happy to keep digging but figured I'd log it.

**Comment by JulianHayward** [comment]
@BevanSin thanks for reporting; awaiting the fix PR
