### ISSUE TITLE
AzDO: Receiving a report per subscription instead of an overall one

### ISSUE THREAD

**Issue by vegazbabz** [JulianHayward/Azure-MG-Sub-Governance-Reporting#134]
We have tried to implement AzGovViz via Azure DevOps. However, it is not working as intended.
It seems like it generates a HTML file for each subscription, and I am not able to find the overall HTML to view the compliance for our tenant like here:
https://www.azadvertizer.net/azgovvizv4/demo/AzGovViz_demo.html

This is an example of our repo and the HTML files (several 100s):
![image](https://user-images.githubusercontent.com/31761897/191518609-e88dc697-68fa-4c96-9965-607c2e216696.png)

If you download and open one of the files, they look like this:
![image](https://user-images.githubusercontent.com/31761897/191520483-81cbbb74-79ef-4ae4-93af-01c9f118d2ed.png)

I have tried to review: https://jacktracey.co.uk/azgovviz-with-azure-devops/

What are we doing wrong since we do not get an overall file, but a file for each subscription?

**Comment by JulianHayward** [comment]
there should be two html files directly in the `wiki` folder:
* AzGovViz_`ManagementGroupId`.html <- _this is the one you are looking for_
* AzGovViz_`ManagementGroupId`_DefinitionInsights.html

**Comment by vegazbabz** [comment]
Thank you @JulianHayward !
I found the AzGovViz_MG.html and it is indeed showing the info I was looking for.
I cannot find the "DefinitionInsights".html - do I need this? The above file looks pretty complete.

**Comment by JulianHayward** [comment]
welcome, which version of AzGovViz are you running? With version >= v6_major_20220912_1 the DefinitionInsights will be created in a dedicated html file (AzGovViz_ManagementGroupId_DefinitionInsights.html), this improves responsiveness/user experience for the main html file AzGovViz_ManagementGroupId.html

**Comment by vegazbabz** [comment]
Alright, thanks for clarifying. We use v6_major_20220803_1, so if we upgrade, we should see 2 dedicated files?
Is it just this part (DefinitionInsights) that will be moved into a dedicated file?
![image](https://user-images.githubusercontent.com/31761897/191594548-401f4af6-6426-47a6-88b1-fca51ca9e122.png)

If yes, we might just use -NoDefinitionInsightsDedicatedHTML parameter - responsiveness seem to still be OK.

Is there any way to only create AzGovViz_MG.html and not one for every single subscription?

Thanks for your huge effort.

**Comment by JulianHayward** [comment]
> Alright, thanks for clarifying. We use v6_major_20220803_1, so if we upgrade, we should see 2 dedicated files? Is it just this part (DefinitionInsights) that will be moved into a dedicated file? ![image](https://user-images.githubusercontent.com/31761897/191594548-401f4af6-6426-47a6-88b1-fca51ca9e122.png)
> 
correct
> If yes, we might just use -NoDefinitionInsightsDedicatedHTML parameter - responsiveness seem to still be OK.
> 
> Is there any way to only create AzGovViz_MG.html and not one for every single subscription? Is it just to use -NoSingleSubscriptionOutput ?
> 
correct
> Thanks for your huge effort.

thanks :)

I guess we can close this one then?
