### ISSUE TITLE
New Storage Account Access Analysis feature make workflow with OIDC time out

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/Azure-MG-Sub-Governance-Reporting#135]
After updating to latest version with Storage Account Access Analysis pipeline with OIDC authentication breaks due to timeout.

**Comment by JulianHayward** [comment]
hmm, I don´t see how the OIDC authentication is related to the script update. In my test GitHub it is working fine. Can you try again please?

**Comment by extmaper** [comment]
It fails after running AzGovViz step for about 33 minutes. Below is error message.

Running the same configuration against a small environment works fine.

![errormsg](https://user-images.githubusercontent.com/56257151/192784626-5a74b6a1-2e8e-439a-85d1-44404c7865fb.png)

**Comment by JulianHayward** [comment]
ok, got it.
ref: [https://github.com/Azure/azure-powershell/issues/17346](https://github.com/Azure/azure-powershell/issues/17346)

**Comment by JulianHayward** [comment]
ok, seems we can good work around:  
https://goodworkaround.com/2021/12/21/another-deep-dive-into-azure-ad-workload-identity-federation-using-github-actions/

may take some time, though..

**Comment by JulianHayward** [comment]
@extmaper can you please try the latest release (see [release notes](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/releases/tag/v6_major_20220930_1))

**Comment by extmaper** [comment]
Works fine after latest update. Thanks for quick fix and really nice work with the storage account analysis feature.
