### ISSUE TITLE
Getting an intermittent access issue to particular storage accounts within the tenant

### ISSUE THREAD

**Issue by jyoung80** [JulianHayward/Azure-MG-Sub-Governance-Reporting#136]
I am seeing intermittent issues with the script running over particular storage accounts in the tenant which ultimately breaks the script.
One example is a storage account in use for Terraform for state, and a couple of other specific use cases.

Processing SA; Subscription: <subname> - Storage Account: <name here>
  Forced DEBUG: spaz01stg077 get comp=list -> AuthorizationFailureThis request is not authorized to perform this operation.
RequestId:a41c5b45-701e-0019-4abc-d3f337000000
Time:2022-09-29T04:30:43.5103681Z -> returning string 'AuthorizationFailure'

This subsequently dies as per below;

Start-Sleep: /home/vsts/.local/share/powershell/Modules/AzAPICall/1.1.24/functions/AzAPICallFunctions.ps1:467
Line |
 467 |                  Start-Sleep -Seconds $sleepSec
     |                                       ~~~~~~~~~
     | Cannot convert 'System.Object[]' to the type 'System.Double'
     | required by parameter 'Seconds'. Specified method is not
     | supported.

##[error]PowerShell exited with code '1'.

The last error output is at 55 seconds sleep so I think when this increments over 60 this causes the conversion to fail.

**Comment by JulianHayward** [comment]
@jyoung80 please try again with the latest release, remember to reset the `NoStorageAccountAccessAnalysis` switch in the variables yaml

**Comment by extmaper** [comment]
I got same error when there was a storage account that was removed during the process when AzGovViz ran.

**Comment by JulianHayward** [comment]
@extmaper does this apply for the latest or previous version?

**Comment by extmaper** [comment]
Yes, got it running latest version. Error looked like this. Verified in the activity log on the subscription in scope that the storage account in the error message was deleted.

![image](https://user-images.githubusercontent.com/56257151/193247817-08b8334d-0ddf-436f-9d89-bc4aee3ae81b.png)

**Comment by JulianHayward** [comment]
nice timing :). Thanks for sharing the exact error - let´s handle that scenario accordingly (next release ..)

**Comment by jyoung80** [comment]
@JulianHayward Working perfectly now - Thankyou!

Apologies for the delay in response - long weekend here in Oz
