### ISSUE TITLE
Storage analysis in AzureChinaCloud fails

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/Azure-MG-Sub-Governance-Reporting#138]
Script fails according to screenshot. Storage account is reported as unknown target endpoint, but storage account exists.

![image](https://user-images.githubusercontent.com/56257151/196447674-dcd620d0-b9c0-4509-9b5e-ced9e23f5557.png)

**Comment by JulianHayward** [comment]
@extmaper thanks for reporting. Can you please update the azGovVizParallel.ps1 param variable `AzAPICallVersion` to `1.1.42` and try again?

<img width="233" alt="image" src="https://user-images.githubusercontent.com/45695032/196522680-d4a95b43-e760-4a98-8557-9f294d79f661.png">

[AzAPICall](https://www.powershellgallery.com/packages/AzAPICall)

**Comment by extmaper** [comment]
@JulianHayward it worked fine with version 1.1.42.
