### ISSUE TITLE
Script failes on databasename with `:` in the name

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/Azure-MG-Sub-Governance-Reporting#139]
While deploying the Azure Governance reporting for a new tenant we come across a fatal error that stops script execution. The errors is as follows ;

!Please report at aka.ms/AzGovViz and provide the following dump
Checking if ResourceType 'microsoft.sql/servers/databases' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/<rgname>/providers/microsoft.sql/servers/<sqlservername>/databases/<databasename> 2022-09-16 10:49:03 copy' - try #1; returned: (StatusCode: '404' (NotFound)) <.code: ''> <.error.code: ''> | <.message: 'The request url contains an invalid character (:).'> <.error.message: ''> - (plain : @***Message=The request url contains an invalid character (:).***) - EXIT

Besides the fact that we can rename the database name, it would be nice if the script logs the error and continues execution

**Comment by JulianHayward** [comment]
please try with branch [networkFeatures]( https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/networkFeatures)

__Changes__ (2022-Oct-24 / Major)

* New feature - Network analysis (__TenantSummary__ and CSV export)
  * Virtual Networks
  * Virtual Network Peerings
* New parameter `-NoResourceProvidersAtAll` - processing Resource Providers in large tenants can consume a lot of memory / increase processing time significantly
* Minor optimizations
* Fix issue #139
* Use [AzAPICall](https://aka.ms/AzAPICall) PowerShell module version 1.1.44

**Comment by MarcelHeek** [comment]
Hi @JulianHayward Thanks for the quick response.

I tried an execution with the networkFeatures branch, but this time the script did not came to the point of the database with the : in the name.

It exits after processing storage account encountering the following issue(s):

_Processing SA; Subscription: <SUBNAME> (<SUBID>) [EnterpriseAgreement_2014-09-01] - Storage Account: <storageaccountname>
  Forced DEBUG: sqlclusterquorum1 get comp=list -> AuthorizationFailureThis request is not authorized to perform this operation.
RequestId:<requestid>
Time:2022-10-25T08:24:35.0289924Z -> returning string 'AuthorizationFailure'
 careblob get restype=service&comp=properties #1 'Unexpected Error' occurred (trying 10 times); sleep 2 seconds
Connection timed out
 careblob get restype=service&comp=properties #2 'Unexpected Error' occurred (trying 10 times); sleep 3 seconds
Connection timed out
 careblob get restype=service&comp=properties #3 'Unexpected Error' occurred (trying 10 times); sleep 5 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#4 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #4 'Unexpected Error' occurred (trying 10 times); sleep 7 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#5 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #5 'Unexpected Error' occurred (trying 10 times); sleep 10 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#6 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #6 'Unexpected Error' occurred (trying 10 times); sleep 13 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#7 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #7 'Unexpected Error' occurred (trying 10 times); sleep 17 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#8 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #8 'Unexpected Error' occurred (trying 10 times); sleep 20 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#9 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #9 'Unexpected Error' occurred (trying 10 times); sleep 25 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#10 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #10 'Unexpected Error' occurred (trying 10 times); sleep 30 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#11 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #11 'Unexpected Error' occurred (tried 5 times)/exit
Exception: /home/runner/work/azure-governance-visualizer/azure-governance-visualizer/tools/pwsh/AzGovVizParallel.ps1:11310
 Line |
11310 |          $storageAccounts | ForEach-Object -Parallel ***
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - check the last console output for details

Error: Error: The process '/usr/bin/pwsh' failed with exit code 1_


I hope you can assist

**Comment by JulianHayward** [comment]
@MarcelHeek Let´s sort the findings :)

* Please confirm that this Storage Account error also occurs with the prod version __v6_major_20221019_1__
* Please run the __v6_major_20221024_1__ version with parameter `-NoStorageAccountAccessAnalysis` to see if the invalid character issue is fixed

**Comment by MarcelHeek** [comment]
@JulianHayward 

With version v6_major_20221019_1 (commit: 7a6e88b81b8365e81ac9eb41cac5d004b380843b) the error with the ':' in the database name is again fatal. It seems to continue on the previous error with the storage account 

Forced DEBUG: sqlclusterquorum1 get comp=list -> AuthorizationFailureThis request is not authorized to perform this operation.

The last option you want me to check does not make sense to me as the invalid character issue is not with collecting data on storage accounts, but in the part that checks the support for diagnostics settings for ResourceTypes.

**Comment by JulianHayward** [comment]
@MarcelHeek 

the second option is to skip the storage account analysis, because the invalid character error happens after the sa analysis.  

But I understand that option 1 has passed the storage account analysis.. without running into unexpectedError: true.  

Can you ping me on LinkedIn?

**Comment by MarcelHeek** [comment]
Tested with 1024 version, issue solved. Waiting for the release, closing the issue.
