### ISSUE TITLE
Typo Fix

### ISSUE THREAD

**Issue by DeadPoolHeartsRR** [JulianHayward/Azure-MG-Sub-Governance-Reporting#14]
Was just reading through the doc and noticed the misspelling for the word schedule, bolded and italicized below:

Azure DevOps Pipeline
The provided example Pipeline is configured to run based on a **_shedule_** (every 6 hours). It will push the AzGovViz markdown output file to the 'wiki' folder in the 'Azure-MG-Sub-Governance-Reporting' Repository which will feed your Wiki.

Looking forward to testing this script out!

**Comment by JulianHayward** [comment]
thank you. fyi new release coming up shortly (bugs, features and especially performance)
