### ISSUE TITLE
script fails on databrick storage accounts 

### ISSUE THREAD

**Issue by emt2600** [JulianHayward/Azure-MG-Sub-Governance-Reporting#140]
The AzGovViz pipeline fails with an error as stated below: 
"AuthorizationPermissionMismatch This request is not authorized to perform this operation using this permission"

This occurs when it tried to access a databricks storage account called:
databricks-rg-*

I was able to fix this issue by adding the error type to the saProperties and listContainers filters in the AzGovVizParallel.ps1 and processStorageAccountAnalysis.ps1 like seen below:

_AzGovVizParallel.ps1 line 11026_
`if($saProperties -eq 'AuthorizationPermissionMismatch' -or $saProperties -eq ...`

_AzGovVizParallel.ps1 line 11051_
`if($listContainers -eq 'AuthorizationPermissionMismatch' -or $listContainers -eq ...`

_processStorageAccountAnalysis.ps1 line 38_
`if($saProperties -eq 'AuthorizationPermissionMismatch' -or $saProperties -eq ...`

_processStorageAccountAnalysis.ps1 line 63_
`if($listContainers -eq 'AuthorizationPermissionMismatch' -or $listContainers -eq ...`

**Comment by JulianHayward** [comment]
@emt2600 great - thanks! 

would be awesome if you could raise a PR against the [networkFeatures](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/networkFeatures) branch. See if the [contribution guide](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/contributionGuide.md) works for you.

**Comment by JulianHayward** [comment]
@emt2600 go?

**Comment by emt2600** [comment]
Sorry! Just got back to this, you should see the PR now - [144](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/pull/144)

**Comment by JulianHayward** [comment]
@emt2600 thanks - merged
