### ISSUE TITLE
Storage Analysis section with 'Unexpected Error' / 'Connection timed out'

### ISSUE THREAD

**Issue by JulianHayward** [JulianHayward/Azure-MG-Sub-Governance-Reporting#145]
Not sure wheter this is in the same script context, but sometimes I get fatal error on this in the Storage Analysis section with `Unexpected Error`

..........
careblob get restype=service&comp=properties #1 'Unexpected Error' occurred (trying 10 times); sleep 2 seconds
Connection timed out
careblob get restype=service&comp=properties #2 'Unexpected Error' occurred (trying 10 times); sleep 3 seconds
Connection timed out
 careblob get restype=service&comp=properties #3 'Unexpected Error' occurred (trying 10 times); sleep 5 seconds
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#4 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #4 'Unexpected Error' occurred (trying 10 times); sleep 7 seconds
......... 
Connection timed out
  Forced DEBUG: careblob get restype=service&comp=properties -> attempt#11 processing: careblob get restype=service&comp=properties uri: 'https://careblob.blob.core.windows.net/?restype=service&comp=properties'
  Forced DEBUG: careblob get restype=service&comp=properties -> unexpectedError: true
 careblob get restype=service&comp=properties #11 'Unexpected Error' occurred (tried 5 times)/exit
Exception: /home/runner/work/azure-governance-visualizer/azure-governance-visualizer/tools/pwsh/AzGovVizParallel.ps1:11310
 Line |
11310 |          $storageAccounts | ForEach-Object -Parallel ***
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - check the last console output for details

_Originally posted by @MarcelHeek in https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/issues/144#issuecomment-1301761614_

**Comment by JulianHayward** [comment]
@MarcelHeek

**Comment by JulianHayward** [comment]
@MarcelHeek pls check the branch

**Comment by MarcelHeek** [comment]
@JulianHayward I did a test run (with the v6_major_20221108_1 branch) against a tenant that experienced this issue, and the result was that the script does not any longer quit with fatal error. So looks better now.

Hope this gets GA soon, so I can get all my tenants on the same version again  👍

**Comment by JulianHayward** [comment]
merged
