### ISSUE TITLE
Update Screenshot | Tenant Summary

### ISSUE THREAD

**Issue by DaFitRobsta** [JulianHayward/Azure-MG-Sub-Governance-Reporting#148]
Hello @JulianHayward, 
Could you please update the screenshot for the Tenant Summary located here: https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#screenshots

I'd like to incorporate your latest Policy features for Azure Landing Zones Policy Version Checker.

Thank you!

**Comment by JulianHayward** [comment]
@DaFitRobsta done - please show me your draft

**Comment by DaFitRobsta** [comment]
This is where I'm referencing your screenshot:
https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/update-alz-custom-policies?branch=pr-en-us-4039
