### ISSUE TITLE
psrule - not reporting tls correctly

### ISSUE THREAD

**Issue by nb2708** [JulianHayward/Azure-MG-Sub-Governance-Reporting#152]
Hi, I've deployed azgovviz for a couple tenants i am working on. On both tenants under psrule, tls is showing as less than 1.2 for nearly every app service and storage account (i.e. for one subscription 68/71 app services are showing as non compliant when they are compliant with tls 1.2).

Not sure if this is an issue with psrule or azgov and whether you may have seen this before? Would really appreciate any help

**Comment by JulianHayward** [comment]
hi, 
there have been some fixes, please try the latest release

**Comment by JulianHayward** [comment]
please see https://github.com/Azure/PSRule.Rules.Azure/issues/1919  
will reference
