### ISSUE TITLE
Issue running AzGovViz in ADO 

### ISSUE THREAD

**Issue by cbezenco** [JulianHayward/Azure-MG-Sub-Governance-Reporting#153]
Getting an error in AzGovViz ADO config after Installing AzAPICall module 

PS> Had to modify pipeline agent to ubuntu-latest as my ADO instance did not have ubuntu-22.04 agent available.

Starting: Run AzGovViz
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.209.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
Generating script.
Formatted command: . '/home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1' -ManagementGroupId Tenant Root Group -CsvDelimiter ';' -OutputPath wiki -SubscriptionQuotaIdWhitelist undefined -DoAzureConsumption -AzureConsumptionPeriod 14 -ExcludedResourceTypesDiagnosticsCapable microsoft.web/certificates -StorageAccountAccessAnalysisSubscriptionTags undefined -StorageAccountAccessAnalysisStorageAccountTags undefined -ScriptPath pwsh
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/a9c778f7-90b0-4a13-b96b-8d11b30ee3ff.ps1'
Saved!
Import-Module -Name /usr/share/az_9.0.1/Az.Accounts/2.10.3/Az.Accounts.psd1 -Global
Clear-AzContext -Scope Process
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Connect-AzAccount -ServicePrincipal -Tenant 7cd45a3f-ea4c-4e6f-9609-580eeeb81dfc -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
Start AzGovViz 09-Dec-2022 13:25:34 (#v6_major_20221207_1)
 Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[2] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.2.7
  PS Version check succeeded
Output/Files will be created in path '/home/vsts/work/1/s/wiki/.'
 Verify 'AzAPICall' (Group)
  'AzAPICall Group' not installed
  Installing AzAPICall module (Group)
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:27938
 Line |
27938 |  …             throw "  Installing '$($module.ModuleName)' module ($($mo …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   Installing 'AzAPICall' module (Group) failed

##[error]PowerShell exited with code '1'.
Finishing: Run AzGovViz

Additional info:
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az365-743'
Current agent version: '2.213.2'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20221204.2'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.212.0)
Downloading task: AzurePowerShell (5.209.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

Starting: Prerequisites check
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/3997c561-e3c9-4b11-a288-bd7975ddcdba.ps1'
CodeRunPlatform: AzureDevOps
outputpath is 'wiki'
Creating directory 'wiki'

    Directory: /home/vsts/work/1/s

UnixMode   User             Group                 LastWriteTime           Size
--------   ----             -----                 -------------           ----
drwxr-xr-x vsts             docker             12/09/2022 13:25           4096
Repository access check
Checking: Project Collection Build Service (dmo-bezencon-net)
Checking: AzGovViz Build Service (dmo-bezencon-net)
subjectDescriptor for 'AzGovViz Build Service (dmo-bezencon-net)': svc.ODFiMTUzYTgtYjYyZi00NTNhLTlmMDUtNjJmOGFmMWIzNDNkOkJ1aWxkOjc4MWI0OTlkLWI1MmUtNDgwNS1hMWI2LWZmMzQwYTc4NzlmYw
'AzGovViz Build Service (dmo-bezencon-net)' (781b499d-b52e-4805-a1b6-ff340a7879fc) permissions for Repository: AzGovViz (22205b38-8cfe-446a-ad7e-56501d089358)
 Contribute: allow (1)
All permissions:
 Bypass policies when completing pull requests: not set
 Bypass policies when pushing: not set
 Contribute: allow (1)
 Contribute to pull requests: not set
 Create branch: not set
 Create tag: allow(inherited) (3)
 Delete or disable repository: not set
 Edit policies: not set
 Force push (rewrite history, delete branches and tags): not set
 Manage notes: not set
 Manage permissions: not set
 Read: allow(inherited) (3)
 Remove others' locks: not set
 Rename repository: not set

Finishing: Prerequisites check

**Comment by JulianHayward** [comment]
at this time only the ubuntu/linux based workers are supported.
If however you have a fix, please contribute/share. Thank you.

**Comment by cbezenco** [comment]
Here is a summary of how I fixed the issue:

1. ADO pipeline definition had to be fixed as ADO does not recognize ubuntu-22.04 yet. You have to set it to ubuntu-latest. 
2. Also the issue seem to indicate a problem during installation of AzAPICall module, the actual error was due to the fact that I was using the management group display name vs the Management Group Id in AzGovViz.variables.yml.

This was really confusing an I lost a few hours so I hope this post can help others who might find similar error message...

**Comment by JulianHayward** [comment]
thanks @cbezenco - 2. should be optimized with the latest pipeline YAML?!
