### ISSUE TITLE
Error during PSRule

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/Azure-MG-Sub-Governance-Reporting#154]
During PSRule part in the script error according to screenshot

![image](https://user-images.githubusercontent.com/56257151/206739366-beada214-0ae6-4f50-a298-bf3cb2feb96f.png)

**Comment by JulianHayward** [comment]
AzGovViz / PSRule integration under review. Findings and decision on how to proceed will be posted soon.
Interesting resource though! Would love to see the resource JSON

**Comment by extmaper** [comment]
@JulianHayward - Removed DoPsRule parameter, error still there in the CustomDataCollection section.

**Comment by JulianHayward** [comment]
@extmaper  please try the latest release and check the logs for 'ConvertFrom-Json' AzAPICall errors / if not dumped please check the related resource /JSON def - thanks!

**Comment by extmaper** [comment]
@JulianHayward - works with latest version. Thanks.

**Comment by JulianHayward** [comment]
@extmaper any 'ConvertFrom-Json' AzAPICall errors? Can you share one of the JSON defs /offline?
