### ISSUE TITLE
AzGovViz in Azure China

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/Azure-MG-Sub-Governance-Reporting#155]
Error running in AzGovViz in Azure China

![image](https://user-images.githubusercontent.com/56257151/207273968-df8d8d1e-b1d3-4529-9131-370e49ecc443.png)

**Comment by JulianHayward** [comment]
thanks - please check latest :)

**Comment by extmaper** [comment]
@JulianHayward  The initial error is resolved, but now I get another one.

![image](https://user-images.githubusercontent.com/56257151/208085916-38ad73b2-d06d-4fdc-af23-3b9850f4c834.png)

**Comment by JulianHayward** [comment]
@extmaper please check the latest release

**Comment by extmaper** [comment]
@JulianHayward - works fine now, thanks.
