### ISSUE TITLE
Missing api version error during subscription processing

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/Azure-MG-Sub-Governance-Reporting#156]
Hi,

After using the latest version 'v6_major_20221222_1' I ran across an fatal issue early in the datacollection. The error is shown below in the screenshot.

![image](https://user-images.githubusercontent.com/84451910/209342129-d8316d40-b50d-4acf-9aa5-aa82f38aca2c.png)

with kind regards,

Marcel Heek

**Comment by JulianHayward** [comment]
@MarcelHeek can you run it with the debugazapicall parameter so that we can see the $uri var used? thanks!

**Comment by MarcelHeek** [comment]
Will do, additionally, let me express that I also get this with this version : v6_major_20221212_1

**Comment by JulianHayward** [comment]
@MarcelHeek need to stick this into the backlog to check for uri containing spaces. The latest release will not try to get resource properties for certificates, but only for 'available Private Endpoint resource types', so your issue should be worked around.

**Comment by JulianHayward** [comment]
@MarcelHeek close?

**Comment by MarcelHeek** [comment]
Sure
