### ISSUE TITLE
Property not found during convert json

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/Azure-MG-Sub-Governance-Reporting#157]
Using version v6_major_20221222_1.

Same resource where json of the resource have been shared before.

![image](https://user-images.githubusercontent.com/56257151/209629083-7611c03f-6d2f-47b2-bb93-8007e2792e0f.png)

**Comment by JulianHayward** [comment]
thanks - should be fixed with v6_major_20221228_2

**Comment by extmaper** [comment]
New error when running latest update.

![image](https://user-images.githubusercontent.com/56257151/209924341-48a8b053-c0f7-44b4-a20e-77023081d5d2.png)

**Comment by JulianHayward** [comment]
@extmaper at what stage does the error occur?

**Comment by extmaper** [comment]
@JulianHayward during this part

![image](https://user-images.githubusercontent.com/56257151/209925374-24926ad7-b70c-4c7d-9dc6-77aed0e92847.png)

**Comment by JulianHayward** [comment]
@extmaper at which step was it?
* Processing Network enrichment <count> Virtual Networks
* Processing Private Endpoints enrichment for <count> Private Endpoint(s) where the Private Endpoint was not returned from the PE API endpoint but from a resource property
* Processing Private Endpoints enrichment for <count> Private Endpoint(s) where the Private Endpoint was returned from the PE API endpoint

**Comment by extmaper** [comment]
@JulianHayward - Processing Private Endpoints enrichment for 58 Private Endpoint(s) where the Private Endpoint was not returned from the PE API endpoint but from a resource property

**Comment by JulianHayward** [comment]
as confirmed, fixed with v6_major_20221229_1
