### ISSUE TITLE
Error: The process '/usr/bin/pwsh' failed with exit code null

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/Azure-MG-Sub-Governance-Reporting#159]
Hi,

I an running the script on a self-hosted GitHub Runner so I can use the Managed Identity of the VM to extract the data of the tenant.
This works OK for a couple of tenants, but for a specific tenant I receive the following. All tenants run the same code (ref : v6_major_20221228_1), and all tenants have the same VM size (Standard_B2s) for the Github runner.
The OS used is:
![image](https://user-images.githubusercontent.com/84451910/210224457-e1eb98f6-8d05-4ec9-b0f6-112a11ff2aad.png)

Here is a screenshot of the error.:
![image](https://user-images.githubusercontent.com/84451910/210223348-dd6a25a3-578f-4ad7-abef-bf98d1018eec.png)

I ran with `-throttleLimit 1 -debugAzAPICall` and without these arguments, no difference in results however.

All I can possibly think of is that the VM running the payload is depleted from available memory and the script just dies.
![image](https://user-images.githubusercontent.com/84451910/210223809-bc011820-93ac-4392-959d-c6278805ea2f.png)

On another tenants I also received a fatal error, but this tenant takes some time to collect and is still running. I will update this issue if any negative results might occur.

I hope we can figure out what is causing this.

**Comment by JulianHayward** [comment]
@MarcelHeek 
it is very likely the memory consumption; please try with a larger SKU and see if it makes the run.  
there are some parameters that may help:
```
    [switch]
    $ShowMemoryUsage,

    [int]
    $CriticalMemoryUsage = 99,
```
you could call the function: `showMemoryUsage` at those stages in the script to get better insights

**Comment by MarcelHeek** [comment]
Ok, will try first with the switches.

**Comment by MarcelHeek** [comment]
Ok, selecting another SKU gives at least a positive result for one tenant. Still checking for the other tenant, but I reckon it should work file as the switch from public to self hosted runner with bigger SKU a gain from 7 GB to 8 GB memory.
Let's assume this fixes it for the other tenant as well and close the issue
