### ISSUE TITLE
After the New update another issue had come -  Could not find a part of the path 'C:\AzGovViz\Azure-MG-Sub-Governance-Reporting-master\pwsh\'.

### ISSUE THREAD

**Issue by WVDAdminTF** [JulianHayward/Azure-MG-Sub-Governance-Reporting#160]
Please advise

End AzGovViz 04-Jan-2023 08:22:59
Checking for errors
Dumping 1 Errors (handled by AzGovViz):

Import-Csv: C:\AzGovViz\Azure-MG-Sub-Governance-Reporting-master\pwsh\AzGovVizParallel.ps1:5337
Line |
5337 |  … tPrevious = Import-Csv -LiteralPath "$($outputPath)$($DirectorySepara …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'C:\AzGovViz\Azure-MG-Sub-Governance-Reporting-master\pwsh\'.

--------------------
AzGovViz completed successful
Don't bother about dumped errors

![ERROR 2](https://user-images.githubusercontent.com/84956733/210602253-9ad57644-fd1a-40af-8f5e-81852e8f689b.jpg)

**Comment by JulianHayward** [comment]
all good :)
```
AzGovViz completed successful
Don't bother about dumped errors
```
FYI: This obviously was the first run against ManagementGroupId xyz, next run that file will be there and it will be able to create a resource fluctuation report (compare previous vs current)..

**Comment by WVDAdminTF** [comment]
Hi Julian,

Thank you for the response, run the 2nd time the script completed with no error. But Now i have 4 Htmls and when i open them they are not showing the information properly, please can you advise on that

![image_2023-01-05_114747183](https://user-images.githubusercontent.com/84956733/210714373-43a62c04-79fc-4b8e-b22a-23847e42fa80.png)

Below is the sample 
![image_2023-01-05_114728700](https://user-images.githubusercontent.com/84956733/210714331-7ced48e7-b4dc-43b0-9bb7-71f9cbba472c.png)

Thank you,

**Comment by WVDAdminTF** [comment]
I have deleted the entire directory and download fresh ZIP file from the Repo - extract and re-executed twice to have no errors and same results the HTML are opening with this format.

Please can you advice

**Comment by JulianHayward** [comment]
hmm, can you download the html file to a client that has internet access (css/images stored on a CDN)?

**Comment by WVDAdminTF** [comment]
Yes, it was the issue of the Client machine not being able to reach the website - https://www.azadvertizer.net/  

It is working fine now. 

Thank you so much

![image_2023-01-05_174353413](https://user-images.githubusercontent.com/84956733/210777779-219fa318-636e-444d-afdb-82c65dc0c406.png)

**Comment by WVDAdminTF** [comment]
Thank you so much, I will close this Issue case as it is resolved
