### ISSUE TITLE
PSRule for Azure - integration paused - PSRule for Azure 

### ISSUE THREAD

**Issue by WVDAdminTF** [JulianHayward/Azure-MG-Sub-Governance-Reporting#162]
Hello Julian,

Sorry to bother you again, I have installed the PSRule module using below commands
Install-Module -Name 'PSRule.Rules.Azure' -Repository PSGallery
Update-Module -Name 'PSRule.Rules.Azure' 

Then ran the command
.\pwsh\AzGovVizParallel.ps1 -DoPSRule

It completed successfully. But I am getting this under the PSRule section
PSRule for Azure - **integration paused** - PSRule for Azure 

![image_2023-01-06_121457509](https://user-images.githubusercontent.com/84956733/210945625-17edc5ae-cb8d-462a-b45c-b63e81363eaa.png)

Please can you guide on this

Regards,
WVDAdminTF

**Comment by JulianHayward** [comment]
@WVDAdminTF yes, integration is paused, updated the [documentation](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/dev#integrate-psrule-for-azure). Working to get it back..

**Comment by WVDAdminTF** [comment]
Hello @JulianHayward  

Please can you let me know if there is any update

Thank you, 

Regards,
WVDAdminTF

**Comment by JulianHayward** [comment]
@WVDAdminTF updates will be published under [releases](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/releases) and [history](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/history.md)
