### ISSUE TITLE
Processing PrivateDNS Zone Links

### ISSUE THREAD

**Issue by bziepke** [JulianHayward/Azure-MG-Sub-Governance-Reporting#168]
DevOps Pipeline fails after several attempts

Checking if ResourceType 'microsoft.network/privatednszones/virtualnetworklinks' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>' - try #8620; returned: (StatusCode: '401' (Unauthorized)) 'InvalidAuthenticationTokenAudience' | 'The access token has been obtained for wrong audience or resource 'https://storage.azure.com'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.' - requesting new bearer token (Storage)
 +Processing new bearer token request 'Storage' "core.windows.net" (https://storage.azure.com)
 +Bearer token 'Storage' (https://storage.azure.com): [tokenRequestProcessed: '02/16/2023 13:18:00']; [expiryDateTime: '02/16/2023 14:18:00']; [timeUntilExpiry: '00:59:59.7886301']
  Forced DEBUG: Checking if ResourceType 'microsoft.network/privatednszones' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net' -> attempt#8080 processing: Checking if ResourceType 'microsoft.network/privatednszones' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net' uri: 'https://management.azure.com//subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/providers/microsoft.insights/diagnosticSettingsCategories?api-version=2021-05-01-preview'
  Forced DEBUG: Checking if ResourceType 'microsoft.network/privatednszones/virtualnetworklinks' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>' -> attempt#8621 processing: Checking if ResourceType 'microsoft.network/privatednszones/virtualnetworklinks' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>' uri: 'https://management.azure.com//subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>/providers/microsoft.insights/diagnosticSettingsCategories?api-version=2021-05-01-preview'
  Forced DEBUG: Checking if ResourceType 'microsoft.network/privatednszones/virtualnetworklinks' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>' -> unexpectedError: true
 Checking if ResourceType 'microsoft.network/privatednszones/virtualnetworklinks' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net/virtualnetworklinks/<LinkName>' #10 'Unexpected Error' occurred (trying 10 times); sleep 30 seconds
Connection timed out
  Forced DEBUG: Checking if ResourceType 'microsoft.network/privatednszones' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net' -> unexpectedError: true
 Checking if ResourceType 'microsoft.network/privatednszones' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/<SubscriptionID>/resourcegroups/<Resourcegroup>/providers/microsoft.network/privatednszones/privatelink.file.core.windows.net' #11 'Unexpected Error' occurred (tried 5 times)/exit
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:3529
Line |
3529 |              $microsoftResourceTypes | ForEach-Object -Parallel {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

##[error]PowerShell exited with code '1'.

**Comment by JulianHayward** [comment]
@bziepke thanks for reporting - are you using the latest AzGovViz version?  
(`$ProductVersion = 'v6_major_20230213_1'` in the param-block of the file `pwsh/AzGovVizParallel.ps1`)

**Comment by JulianHayward** [comment]
@bziepke please provide the error dmp from the run with the latest version

**Comment by JulianHayward** [comment]
@bziepke can you please update?
