### ISSUE TITLE
Az context error

### ISSUE THREAD

**Issue by ramuvr** [JulianHayward/Azure-MG-Sub-Governance-Reporting#169]
**AzGovViz version**
v6_major_20230213_1

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
Occasionally getting the below error on Devops pipeline run 

``
Check Az context failed: Az context is not set to any Subscription
  Set Az context to a subscription by running: Set-AzContext -subscription <subscriptionId> (run Get-AzSubscription to get the list of available Subscriptions). When done re-run the script
  OR
  Use parameter -SubscriptionId4AzContext - e.g. .\AzGovVizParallel.ps1 -SubscriptionId4AzContext <subscriptionId>
Exception: /home/vsts/.local/share/powershell/Modules/AzAPICall/1.1.68/functions/AzAPICallFunctions.ps1:1859
Line |
1859 |          Throw 'Error - check the last console output for details'
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

##[error]PowerShell exited with code '1'.
Finishing: Run AzGovViz
``

**Screenshots**

**Additional context**

**Comment by ramuvr** [comment]
<img width="1718" alt="Screenshot 2023-02-23 201734" src="https://user-images.githubusercontent.com/27629864/220903718-adeaaf71-2eb7-4d92-a64e-5c12298f43d4.png">

**Comment by JulianHayward** [comment]
@ramuvr did you try this?
![image](https://user-images.githubusercontent.com/45695032/220905885-93d2df0c-0c2c-46a3-b714-e8ba6c633070.png)

[parameters ref](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#parameters)

**Comment by ramuvr** [comment]
Hi @JulianHayward I am running this as a pipeline so wasn't sure where to add, I have tried adding it to the AzGovViz.variables.yml under parameters but the pipeline ignored the one I specified under default and took a random subscription when it ran. 
Where else should I specify the parameter or should it go under variables?

**Comment by JulianHayward** [comment]
@ramuvr almost :) it is a variable in [AzGovViz.variables.yml](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/.azuredevops/pipelines/AzGovViz.variables.yml) (already exists in the YAML but is not configured by default)
<img width="314" alt="image" src="https://user-images.githubusercontent.com/45695032/221108718-aeea24cf-af0e-47d8-bf63-4710ac3d0c61.png">
Let´s update the error return with more precise information how/where to set the parameter - thanks!

**Comment by ramuvr** [comment]
@JulianHayward Sorry got distracted in between work. I had added it as variable without realizing it was already present. Now I removed it and used the variable you had in the file and that worked!! Thanks so much. One less thing to worry. :)
