### ISSUE TITLE
WebApp Deploy Task not working in Azure DevOps

### ISSUE THREAD

**Issue by DaniduWeerasinghe911** [JulianHayward/Azure-MG-Sub-Governance-Reporting#173]
**AzGovViz version**
please only report bug if you are running the latest version of AzGovViz

**CodeRunPlatform**
 Azure DevOps

**Describe the bug**
Even after we provided all the required information for the webapp deploy. Deployment task failed when trying to zip the html files.

Did some troubleshooting and found out. 

it's because we use Ubuntu build agents. They are somewhat case sensitive. because of that its failing :(

As an example.

Mangement group Name is - Dckloud

HTML File Create - AzGovViz_Dckloud.html

Zip Task in Web Deploy Looking for - AzGovViz_dckloud.html

**first letter lowercase in management group name ** 

**Screenshots**

I cannot share the screenshot it may reveal some confidential information

**Additional context**
As a fix I ended up doing using lowercase for the mg name. Hopefully you can append it to the latest version

**Comment by JulianHayward** [comment]
@DaniduWeerasinghe911 cannot reproduce the issue (using a MG with camelCase MGId), please ping me on LinkedIn

**Comment by JulianHayward** [comment]
fixed: v6_major_20230308_3
