### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by lpalerm** [JulianHayward/Azure-MG-Sub-Governance-Reporting#180]
**AzGovViz version**
Running latest version

**CodeRunPlatform**
GitHub Action

**Describe the bug**
Workflow ran for 6 hours.  Error in job Run Azure Governence Visualizer:  Error: The operation was canceled.
Summary Error: Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Screenshots**
![image](https://user-images.githubusercontent.com/23060083/231155866-7df4f589-12e5-4829-976a-2bf4210475f0.png)

**Additional context**

**Comment by JulianHayward** [comment]
@lpalerm the GitHub provided runners come with 7GB, try to double that? difficult to estimate without knowing your overall subscription/data amounts.

**Comment by lpalerm** [comment]
Thanks Julian....I added a workflow dispatch so that I can run it for each of the management groups under the tenant, instead of running it for the whole tenant.  Thanks for all your work, this is awesome and I have already found several items to address from just 2 of our 150 subscriptions!
