### ISSUE TITLE
No content being published to Web App

### ISSUE THREAD

**Issue by ashley-kainos** [JulianHayward/Azure-MG-Sub-Governance-Reporting#182]
**AzGovViz version**
running latest version

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
Pipeline runs successfully up to the publish to Html stage, it then shows this: 
Evaluating: and(succeeded(), eq(variables['WebAppPublish'], 'true'))
Expanded: and(True, eq('', 'true'))
Result: False
and then finishes the pipeline successfully. 
When you go to the web app and browser the web site it show as no content published

**Screenshots**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/109275604/232770490-cbbaf097-001f-4533-8bf8-344880aa7453.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/109275604/232770729-0b4540a9-2ad4-474b-8215-c052a54d3f3c.png">

**Additional context**
all permissions have been double checked but just can't figure whats causing this.

**Comment by JulianHayward** [comment]
@ashley-kainos in the `AzGovViz.variables.yml` the variable `WebAppPublish` is set to `true`?

**Comment by ashley-kainos** [comment]
Thank you for this, I was missing that value
