### ISSUE TITLE
Pipeline does not complete

### ISSUE THREAD

**Issue by thefeds-nau** [JulianHayward/Azure-MG-Sub-Governance-Reporting#184]
**AzGovViz version**
Azure Governance Visualizer version is up to date '6.1.0'

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
Raw log file attached

**Screenshots**
![image](https://user-images.githubusercontent.com/67394848/233448295-2338f380-dd5b-43df-8e72-de212fdf9f80.png)
**Additional context**
Trying to run from ADO using a Service Principal, read documentation and confirmed permissions are ok. I have used this same SP on previous versions of AzGovViz. I am now trying to complete the set up in a new ADO Project to share with my team. I would like to have the wiki built and publish to Azure Web App but this Run Azure Governance Visualizer step fails to complete. any advice/assistance would be great.

**Comment by JulianHayward** [comment]
@thefeds-nau please try with the [dev branch](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/dev)
