### ISSUE TITLE
PSRule integration, will it return (soon)?

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/Azure-MG-Sub-Governance-Reporting#187]
Hi,

today I was asked a question which I could have answered by using the PSRule for Azure integration. I know it was paused for a valid reason as it produces incorrect information, but I am wondering if it will ever return (and hopefully soon) as I think that this info is like a pot of gold for doing governance over an azure tenant. It delivers more information then the Azure Advisor if I am not mistaken.

What are your thoughts on this feature @JulianHayward?

**Comment by JulianHayward** [comment]
@MarcelHeek we cannot commit to anything, yet. But @BernieWhite and me still have it on the 'list' :).
