### ISSUE TITLE
Access to the path '/home/vsts/work/1/s/wiki/' is denied.

### ISSUE THREAD

**Issue by ahethaysham** [JulianHayward/Azure-MG-Sub-Governance-Reporting#191]
Import-Csv: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:5734
Line |
5734 |  … tPrevious = Import-Csv -LiteralPath "$($outputPath)$($DirectorySepara …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path '/home/vsts/work/1/s/wiki/' is denied.

Get-Package: No match was found for the specified search criteria and module names
'AzAPICall'.

**Comment by JulianHayward** [comment]
@ahethaysham is there more output, like:

```
Azure Governance Visualizer completed successful
Don't bother about dumped errors
```

**Comment by ahethaysham** [comment]
Hi @JulianHayward yes, I do get the message. But when i push to wiki, i am not getting the content properly and hence i assumed there are issues with the run

**Comment by JulianHayward** [comment]
@ahethaysham I am always happy to help but the given information is too thin, please reopen the issue with a proper description / fill the sections in the issue form - thanks

**Comment by ahethaysham** [comment]
Sure, thanks!
