### ISSUE TITLE
Scoping AAD and/or Graph read rights to an AU?

### ISSUE THREAD

**Issue by cpen-blm** [JulianHayward/Azure-MG-Sub-Governance-Reporting#192]
We need to be able to scope the read rights of the service principal to just an AU within AAD (we have this deployed to GitHub and are using Actions).

I can't seem to find any info in the Microsoft documentation relating to scoping AAD read rights of the SP down further to an AU - can you please provide insight or even another way?

We do not have tenant access and are a business unit under the tenant with many systems, so being able to run this app at our level without having to manually run it would be helpful. We do have access to our own AU within AAD.

Thanks!

**Comment by JulianHayward** [comment]
@cpen-blm I do not have a solution handy, if you find a way to accomplish please post back - thanks.
close for now?

**Comment by cpen-blm** [comment]
I guess, the folks at the tenant don't seem to know either so maybe we cannot use your app which would be a shame as it is helpful.
