### ISSUE TITLE
AzAPICall module install fails if DoAzureConsumption is set to false

### ISSUE THREAD

**Issue by kouvo** [JulianHayward/Azure-MG-Sub-Governance-Reporting#195]
**AzGovViz version**
6.2.0

**CodeRunPlatform**
Azure DevOps

**Describe the bug**

AzAPICall module install fails if DoAzureConsumption is set to false:

 Verify 'AzAPICall' (false)
  'AzAPICall false' not installed
  Installing AzAPICall module (false)
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:29090
 Line |
29090 |  …             throw "  Installing '$($module.ModuleName)' module ($($mo …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   Installing 'AzAPICall' module (false) failed

##[error]PowerShell exited with code '1'.

**Comment by JulianHayward** [comment]
@kouvo are you using the latest [AzGovViz.pipeline.yml](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/.azuredevops/pipelines/AzGovViz.pipeline.yml)?

**Comment by kouvo** [comment]
@JulianHayward apparently not - I had pipeline files in .gitignore. Thanks for quick reply 💯
