### ISSUE TITLE
Exception raised when "Caching built-in Policy and RBAC Role definitions" step

### ISSUE THREAD

**Issue by RodrigoBrCrIntm** [JulianHayward/Azure-MG-Sub-Governance-Reporting#198]
**AzGovViz version**
6.2.1

**CodeRunPlatform**
Visual Studio Code
Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.20348
Sandboxed: Yes

**Describe the bug**
When I run the script , it starts gathering information from the root management group of my Azure tenant but it stops at this point:

Getting orphaned/unused resources (ARG) processing duration: 0.0894643483333333 minutes (5.3678609 seconds) 
Caching built-in Policy and RBAC Role definitions
- - - - - - - - - - - - - - - - - - - - 
!Please report at aka.ms/AzGovViz and provide the following dump
[AzAPICallErrorHandler 1.1.72] Caching built-in Role definitions try #1; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidSubscriptionId'> | <.message: ''> <.error.message: 'The provided subscription identifier 'providers' is malformed or invalid.'> - (plain : @{error=}) - AzAPICall: Stop
Parameters:
accountType:ServicePrincipal
azAccountsVersion:2.12.3
azAPICallModuleVersion:1.1.72
codeRunPlatform:Console
debugAzAPICall:False
debugWriteMethod:Host
DoAzureConsumption:False
DoNotIncludeResourceGroupsAndResourcesOnRBAC:False
DoNotIncludeResourceGroupsOnPolicy:False
DoNotShowRoleAssignmentsUserData:False
DoPSRule:False
GitHubActionsOIDC:False
gitHubRepository:aka.ms/AzGovViz
HierarchyMapOnly:False
LargeTenant:False
ManagementGroupsOnly:False
NoALZPolicyVersionChecker:False
NoJsonExport:False
NoMDfCSecureScore:False
NoNetwork:False
NoPolicyComplianceStates:False
NoResourceProvidersAtAll:False
NoResourceProvidersDetailed:False
NoResources:False
NoStorageAccountAccessAnalysis:False
onAzureDevOps:False
onAzureDevOpsOrGitHubActions:False
onGitHubActions:False
PolicyAtScopeOnly:False
ProductVersion:6.2.1
PSRuleFailedOnly:False
psVersion:7.3.5
RBACAtScopeOnly:False
ThrottleLimit:10
userType:n/a
writeMethod:Host
[AzAPICallErrorHandler 1.1.72] Caching built-in Role definitions try #1; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidSubscriptionId'> | <.message: ''> <.error.message: 'The provided subscription identifier 'providers' is malformed or invalid.'>  - unhandledErrorAction: Stop
Exception: C:\Users\UsuarioAdmin\Desktop\Repos\Nueva carpeta\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:1846:5
Line |
1846 |      $arrayBuiltInCaching | ForEach-Object -Parallel {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Additional context**
I have tried to execute different parameters with the same result. It's an environment with less than 500 subscription and I am pointing to the root management group of my Azure tenant.

.\AzGovVizParallel.ps1 -ManagementGroupId <my-root-management-group-id> -OutputPath "C:\AuditResults"
.\AzGovVizParallel.ps1 -ManagementGroupId <my-root-management-group-id> -OutputPath "C:\AuditResults" -DoTranscript -DoAzureConsumption -ShowMemoryUsage
.\AzGovVizParallel.ps1 -ManagementGroupId <my-root-management-group-id> -OutputPath "C:\AuditResults" -AzureConsumptionPeriod 7
.\AzGovVizParallel.ps1 -ManagementGroupId <my-root-management-group-id> -OutputPath "C:\AuditResults" -AzureConsumptionPeriod 30

**Comment by JulianHayward** [comment]
@RodrigoBrCrIntm thanks for reporting. This sounds odd.. Can you try using the parameter `-SubscriptionId4AzContext` passing in a subscription id? (just to make sure: the parameter `-ManagementGroupId` expects a value)

e.g. `.\pwsh\azGovVizParallel.ps1 -ManagementGroupId '<managementGroupId>' -SubscriptionId4AzContext '<subScriptionId>'`
