### ISSUE TITLE
Feature request: support GitLab pipelines

### ISSUE THREAD

**Issue by erisnar** [JulianHayward/Azure-MG-Sub-Governance-Reporting#200]
Hello!

We run AzGovViz in a GitLab environment. We are able to execute the powershell scripts in our pipelines since GitLab Pipelines and GitHub Actions use similar syntax. This is achieved by setting the environment variable `$env:GITHUB_ACTIONS` used in the AzAPICall funciton.

https://www.powershellgallery.com/packages/AzAPICall/1.1.72/Content/functions%5CAzAPICallFunctions.ps1 line 2033.

Maybe we could extend the AzAPICall function to also include GITLAB_PIPELINES or something similar?

We created GitLab CI-templates based on the provided GitHub Actions workflows.

**Comment by JulianHayward** [comment]
Hello @erisnar,
finally :) was waiting for someone to come up with a GitLab pipeline and identifier. Let´s connect on LinkedIn and take action?

**Comment by erisnar** [comment]
Yes!

There are a lot of built in environment variables for GitLab. We could use 

`GITLAB_CI | Available for all jobs executed in CI/CD. true when available.`

https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by JulianHayward** [comment]
moving to backlog
