### ISSUE TITLE
AzAPICall Module Validation Failing

### ISSUE THREAD

**Issue by cocallaw** [JulianHayward/Azure-MG-Sub-Governance-Reporting#204]
**AzGovViz version**
6.3.0

**CodeRunPlatform**
PowerShell 7.3.6
Windows Terminal 
AAD User Account 

**Describe the bug**
AzGovVizParallel.ps1 fails to complete validation check for AzAPICall Module, even though current version (1.1.75) and specified version (1.1.72) are currently installed. When prompted by the script to install the module by typing y, I can see the installation process occurring, but validation check does not pass and I am asked to install again. 

**Screenshots**
Error Output 

```pwsh
Start Azure Governance Visualizer 19-Jul-2023 16:18:44 (#6.3.0)
Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[3] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.3.6
  PS Version check succeeded
Output/Files will be created in path 'C:\Source\test\.'
 Verify 'AzAPICall' (1.1.72)
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall 1.1.72' not installed
  Do you want to install AzAPICall module (1.1.72) from the PowerShell Gallery? (y/n): y
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall 1.1.72' not installed
  Do you want to install AzAPICall module (1.1.72) from the PowerShell Gallery? (y/n): y
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall 1.1.72' not installed
  Do you want to install AzAPICall module (1.1.72) from the PowerShell Gallery? (y/n): y
 Managing 'AzAPICall' failed (tried 3x)
Exception: C:\Source\Local\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:29078
 Line |
29078 |                  throw " Managing '$($module.ModuleName)' failed"
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  Managing 'AzAPICall' failed
```

<img width="588" alt="image" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/11371083/2cd6527d-1999-4670-85ec-299a57bbaf0d">

<br/>

**Additional context**
Reviewing the output of `Get-Module -ListAvailable` it appears that the AzAPICall Module is not being installed for PowerShell 7 Core but the native Windows PowerShell desktop version.

**Comment by netkrish80** [comment]
Hi I also facing the same issue. 

Start Azure Governance Visualizer 20-Jul-2023 16:30:56 (#6.2.1)
Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[3] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.3.6
  PS Version check succeeded
Output/Files will be created in path 'C:\Azure\Reporting\Azure-MG-Sub-Governance-Reporting-master\Azure-MG-Sub-Governance-Reporting-master\pwsh\.'
 Verify 'AzAPICall' (Group)
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall Group' not installed
  Do you want to install AzAPICall module (Group) from the PowerShell Gallery? (y/n): y
Exception: C:\Azure\Reporting\Azure-MG-Sub-Governance-Reporting-master\Azure-MG-Sub-Governance-Reporting-master\pwsh\AzGovVizParallel.ps1:29114:33
 Line |
29114 |  …             throw "  'Install-Module -Name $($module.ModuleName) -Req …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   'Install-Module -Name AzAPICall -RequiredVersion Group' failed

**Comment by JulianHayward** [comment]
@cocallaw agree this should be fixed/handled differently. As a workaround please simply uninstall the 1.1.75 version then it should work.
@netkrish80 I guess you are passing a value (string, bool, etc.) to a switch parameter which causes this behavior

**Comment by cocallaw** [comment]
@JulianHayward adding more detail and update
- Reviewed prerequisites 
- Ran `Install-Module -Name AzAPICall` which installed 1.1.75 current version 
- Started AzGovVizParallel.ps1 script 
- Received validation error that AzAPICall module was not installed
- Entered Y to install module
- Validation loop occurred as documented previously, ending with exception
- Ran `Get-Module -ListAvailable` and saw that both 1.1.75 and 1.1.72 were installed 
- Created this GitHub Issue 
- Ran `Uninstall-Module -Name AzAPICall -AllVersions`
- Verified that all versions were removed with `Get-Module -ListAvailable`, and restarted PS Session
- Started AzGovVizParallel.ps1 script 
- Received validation error that AzAPICall module was not installed
- Entered Y to install module
- Module installed properly and script continued __successfully__

**Comment by cocallaw** [comment]
@netkrish80 Please try running `Uninstall-Module -Name AzAPICall -AllVersions`, then relaunch your PowerShell session and try to run the AzGovVizParallel.ps1 script again

**Comment by JulianHayward** [comment]
thanks @cocallaw - updated [readme](https://github.com/julianhayward/azure-mg-sub-governance-reporting#powershell) and [setup](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup.md#powershell--azure-powershell-modules) accordingly (hope so :))

**Comment by netkrish80** [comment]
@cocallaw  and @JulianHayward thank you for you suggestioin. After uninstall it worked.

**Comment by JulianHayward** [comment]
seems all are happy :) Thanks - closing..
