### ISSUE TITLE
##[error]Unable to locate executable file: 'pwsh'. 

### ISSUE THREAD

**Issue by ashley-kainos** [JulianHayward/Azure-MG-Sub-Governance-Reporting#205]
**AzGovViz version**
please only report bug if you are running the latest version of AzGovViz

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
##[error]Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Screenshots**
<img width="803" alt="image" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/109275604/35de69a4-1314-448d-9c42-95e0f64c797e">

**Additional context**

**Comment by JulianHayward** [comment]
@ashley-kainos did you precisely follow the [setup guide](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup.md)? Have you changed the pipeline.yml file?

**Comment by ashley-kainos** [comment]
Hi, 

Yes followed the guide, double checked it so don't think I've missing anything. 
The only thing in pipeline I changed was adding the service connection and Management group ID and teh web app items, teh path to pwsh folder is the default, and is in the root of my repo

**Comment by JulianHayward** [comment]
so if you run it on a ms hosted / the default agent then it works - right?

**Comment by ashley-kainos** [comment]
If left as default I get ##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

I have filled out the form and waiting on reply

**Comment by JulianHayward** [comment]
all right, so the issue is caused by your self-hosted worker. Crossing fingers for your request. Will close - ok?

**Comment by JulianHayward** [comment]
surely you can use a self-hosted, but set it up correctly :)
