### ISSUE TITLE
Fixing the AZAPICall Issue

### ISSUE THREAD

**Issue by clifpi** [JulianHayward/Azure-MG-Sub-Governance-Reporting#206]
Hi,
I hope all is well! I have a new version of AZAPICall module and it looks like it wants to install an older version. Not sure how to stop this loop..Please let me know your thoughts when you have a moment. 

PS C:\temp\Azure-MG-Sub-Governance-Reporting-master\pwsh> .\AzGovVizParallel.ps1
Start Azure Governance Visualizer 01-Aug-2023 12:47:03 (#6.3.0)
Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[3] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.3.4
  PS Version check succeeded
Output/Files will be created in path 'C:\temp\Azure-MG-Sub-Governance-Reporting-master\pwsh\.'
 Verify 'AzAPICall' (1.1.72)
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall 1.1.72' not installed
  Do you want to install AzAPICall module (1.1.72) from the PowerShell Gallery? (y/n): y
  AzAPICall - Deviating module version 1.1.75
  'AzAPICall 1.1.72' not installed
  Do you want to install AzAPICall module (1.1.72) from the PowerShell Gallery? (y/n):

**Comment by JulianHayward** [comment]
hi @clifpi for the moment please remove/uninstall the v1.1.75 version or update the AzGovVizParallel.ps1.ps1 param block and change the `AzAPICallVersion` value to 1.1.75

**Comment by JulianHayward** [comment]
@clifpi  please update

**Comment by JulianHayward** [comment]
strike 2 :)

**Comment by JulianHayward** [comment]
closed / no reply
