### ISSUE TITLE
PSRule integration has been paused

### ISSUE THREAD

**Issue by jobbio** [JulianHayward/Azure-MG-Sub-Governance-Reporting#208]
Regardless of the PSRule flag I use, I get this message in the script:

I haven't tried any other method other than interactive member user

PSRule integration has been paused
Azure Governance Visualizer leveraged the Invoke-PSRule cmdlet, but there are certain [resource types](https://github.com/Azure/PSRule.Rules.Azure/blob/ab0910359c1b9826d8134041d5ca997f6195fc58/src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1#L1582) where also child resources need to be queried to achieve full rule evaluation.

Is there some way to bypass this and at least get the results without child resources?

**Comment by JulianHayward** [comment]
@jobbio sorry, but not at this point.
