### ISSUE TITLE
-NoNetwork doesnt work

### ISSUE THREAD

**Issue by jaypee1990** [JulianHayward/Azure-MG-Sub-Governance-Reporting#212]
**AzGovViz version**
please only report bug if you are running the latest version of AzGovViz

**CodeRunPlatform**
GitHub Action via AzGovViz accelerator

**Describe the bug**
When running the tool via github actions, it creates the webapp with default page "AzGovViz_<mgname>.html" but doesnt actually have the html file "AzGovViz_<mgname>.html" in the wwwroot folder. Hence it moves to hostingstart.html and shows the default page.

When ran the script manually, it ended up with error
**0 'Available Private Endpoint Types' - Please use another Subscription for the AzContext (current subscriptionId: '**************************') -> use parameter: -SubscriptionId4AzContext '<subscriptionId>'**
even when using the parameter or changing the value within the AzGovVizParallel.ps1, it fails with same error.

**Screenshots**

![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/98926476/d51dadbc-4e35-4c8c-8714-1f015fe71165)

**Additional context**

**Comment by JulianHayward** [comment]
the parameter does not skip the PE processing,
@jaypee1990 as taken offline; RBAC Reader requirement was not met. /solved
