### ISSUE TITLE
The resource type could not be found in the namespace 'microsoft.datafactory' for api version '2021-05-01-preview

### ISSUE THREAD

**Issue by hli07** [JulianHayward/Azure-MG-Sub-Governance-Reporting#216]
**AzGovViz version**
v6_major_20230330_1

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
[AzAPICallErrorHandler 1.1.72] Checking if ResourceType 'microsoft.datafactory/datafactories' is capable for Resource Diagnostics using 1 ResourceId: '/subscriptions/xxx-xxx-xxx-xxx-xxx/resourcegroups/atsselfservicegroup/providers/microsoft.datafactory/datafactories/copyfactory-78x' try #1; return: (StatusCode: '404' (NotFound)) <.code: ''> <.error.code: 'InvalidResourceType'> | <.message: ''> <.error.message:  #'The resource type could not be found in the namespace 'microsoft.datafactory' for api version '2021-05-01-preview'.'>  - unhandledErrorAction: Stop
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:4028
Line |
4028 |              $microsoftResourceTypes | ForEach-Object -Parallel {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

##[error]PowerShell exited with code '1'.

**Screenshots**
<img width="1075" alt="Screenshot 2023-11-08 at 18 09 26" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/38422857/46dda1c6-07b5-4c08-8b1a-5e5e4ff263f4">

**Additional context**
I can confirm that the actual datafactory azure resource called: **copyfactory-78x** does not exist anymore. But why would it reminisce about it when its not there anymore. Does it maybe have to do with the api version '2021-05-01-preview?

**Comment by JulianHayward** [comment]
@hli07 thanks for reporting, let me fix that [AzAPICall ref handler](https://github.com/JulianHayward/AzAPICall/blob/dc226481c1b060df82cadae4e0a541ce5b2f2f2a/pwsh/module/dev/AzAPICall/functions/AzAPICallRuleSet.ps1#L702) - meanwhile deleted resources are actually handled but in this case the errorcode seems to deviate from the yet known standard(s) :) ), I guess that in the next run the error will disappear as the resource will not be picked up.. let me know.

**Comment by hli07** [comment]
Hi @JulianHayward, thank you very much for the prompt response. 

I have a azure pipeline thats scheduled to run every day twice but only noticed the failure today.

**I guess that in the next run the error will disappear as the resource will not be picked up.. let me know.**
So looking into the last working pipeline which was on the 21st September 2023, it has failing every since, meaning up to today

**Comment by JulianHayward** [comment]
@hli07 hmm, always with this error then I assume?

What if you run this against that sub/rg is the meanwhile deleted resource getting listed?

```
Get-AzResource -ResourceGroupName testRG 
```
or even better if you try with the api: https://learn.microsoft.com/en-us/rest/api/resources/resources/list?view=rest-resources-2021-04-01

[azgvz ref](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/98f9171d70df17b3d11a8a00a9e46b8234d74f4f/pwsh/dev/functions/dataCollection/dataCollectionFunctions.ps1#L512)

**Comment by hli07** [comment]
> @hli07 hmm, always with this error then I assume?
> 
> What if you run this against that sub/rg is the meanwhile deleted resource getting listed?
> 
> ```
> Get-AzResource -ResourceGroupName testRG 
> ```
> 
> or even better if you try with the api: https://learn.microsoft.com/en-us/rest/api/resources/resources/list?view=rest-resources-2021-04-01
> 
> [azgvz ref](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/98f9171d70df17b3d11a8a00a9e46b8234d74f4f/pwsh/dev/functions/dataCollection/dataCollectionFunctions.ps1#L512)


**So all the scheduled pipelines had failed with the same error:**
<img width="1179" alt="Screenshot 2023-11-08 at 20 01 34" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/38422857/c3fe97e6-1b50-4e8c-8288-3a3db1457f40">


**Now I ran the pipeline manually:**
<img width="1286" alt="Screenshot 2023-11-08 at 20 02 25" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/38422857/7cb968af-8d2e-430d-a9fb-8343ef5071a6">


**First manually run pipeline error:**
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:29124
 Line |
29124 |  …             throw "  Installing '$($module.ModuleName)' module ($($mo …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   Installing 'AzAPICall' module (1.1.72) failed


**Second manually run pipeline:**
Still running, will be able to tell more after 20m+

**Comment by hli07** [comment]
Hi @JulianHayward, so the good news is its still running and past the point where it failed before.
<img width="1020" alt="Screenshot 2023-11-08 at 20 29 53" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/38422857/64a2c58b-0460-42c7-831c-24b1b10f6add">

I got another pipeline with another goviz webapp failing but with a different error compared to the error that I posted for this issue. 

Do you want me to create another issue or just paste it here?

**Comment by hli07** [comment]
I got another pipeline with another goviz webapp failing but with a different error (**_see below_**) that I posted for this issue. I ran that pipeline manually multiple times and got this error: 

```
Exception: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:34129
 Line |
34129 |              Throw $throwmsg
      |              ~~~~~~~~~~~~~~~
      | 0 'Available Private Endpoint Types' - Please use another Subscription
      | for the AzContext (current subscriptionId:
      | 'xxx-xxx-xxx-xxx-xxx') -> use parameter:
      | -SubscriptionId4AzContext '<subscriptionId>'

##[error]PowerShell exited with code '1'.
``` 

Quick question on this error, I have noticed in the variables that this is randomised

```
  # Define the Subscription Id to use for AzContext (default is to use a **random Subscription Id**)
  - name: SubscriptionId4AzContext
    # String | example: value: "<your-Subscription-Id>"
    value:
``` 
Is it better to always by default point to a (if existing) subscription or leave it empty? What from I am seeing is if I don't point to a subscription, this error will always re-occur, since I ran the pipeline multiple times and it took this same subscription multiple times? 

Apologise if I am imposing on this issue to another issue, do you want me to create another issue or could we continue here?

**Comment by hli07** [comment]
I guess I have solved my own problems lol, but thanks anyways @JulianHayward :)
