### ISSUE TITLE
Errors during Script run

### ISSUE THREAD

**Issue by steph409** [JulianHayward/Azure-MG-Sub-Governance-Reporting#229]
Hi,

Execution of the azure devops pipeline is successful, but there are a couple of errors in the script execution. The problem seems to be that some tenants from microsoft are hardcoded. The censored ID ending with c12 is my tenant id.

```
\u0027https://sts.windows.net/00000000-0000-0000-0000-0000000c12/\u0027. It must match one of the tenants \u0027https://sts.windows.net/2f4a9838-26b7-47ee-be60-ccc1fdec5953/,https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/\u0027 associated with this subscription. Please use any authority (URL) from \u0027https://login.windows.net/2f4a9838-26b7-47ee-be60-ccc1fdec5953,https://login.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d\u0027 to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."   } }
```

<img width="808" alt="image" src="https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/33083326/d0964016-91fe-4656-808d-f804d5d7a1fa">

The following line seems to be part of the problem:

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/d777afa240d5a8c94d4fa4935375c12de02781f5/pwsh/dev/devAzGovVizParallel.ps1#L627

**Comment by JulianHayward** [comment]
@steph409 if you can see this then all is good (it´s only dumping errors that have been handled by the azapical ..
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/45695032/67469081-250c-4b8c-929e-0bac94ca750e)
