### ISSUE TITLE
PIM active role assignments

### ISSUE THREAD

**Issue by neok-g** [JulianHayward/Azure-MG-Sub-Governance-Reporting#232]
**AzGovViz version**
6.4.5.

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
I am examining the report 'Role assignment related entries' and specially looking for **_active_** role assignments managed in PIM. They seem to be missing in this report.

First scenario is a securitygroup ACL_PG_AzureCostManagement which has 2 role assignments for roles 'Cost Management Reader' and 'Billing Reader' on scope tenant root group managed in PIM see first screenshot. These are active PIM role assignments with both a start and end date since they are managed within PIM. In second screenshot you see the output for these role assignments in the AzGovViz report. As you can see the PIM related columns are empty. For simplicity's sake I have hidden irrelevant columns.

Second scenario are some service principals that belong to managed identities created by Azure for some Azure policies with a remediation task see screenshot 3. As you can see these identities have an active role assignment with a permanent end date since they are created by Azure policy outside PIM.

**Screenshots**
**Screenshot 1 - PIM - Active PIM role assignments securitygroup**
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/9d6a43ef-79bb-4fac-bca8-910aa616da0c)

**Screenshot 2 - AzGovViz Active PIM role assignments securitygroup**
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/1307f2ff-7dbb-4b6c-8da9-04b1491180b9)

**Screenshot 3 - PIM - Active role assignments service principal**
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/338f7bcb-0b0c-4099-a0fb-68cb84a35b3a)

Screenshot 4 - AzGovViz Role assignments service principals
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/dc255512-e07d-4276-8b3f-bffd82aae90f)

 
**Additional context**

**Comment by JulianHayward** [comment]
@neok-g can you check the createdBy/updatedBy columns for the role assignments in doubt? (*_roleAssignments.csv)

**Comment by neok-g** [comment]
@JulianHayward Thanks for your response.

There is no updatedBy column, only createdOn and createdBy.

For the first scenario (group ACL_PG_AzureCostManagement) both columns are empty.

For second scenario (serviceprincipals/ managed identities) the createdOn contains a datetime and createdBy contains ObjectType: SP APP INT

**Comment by JulianHayward** [comment]
hmm can you please verify for scenario1:

```
$roleAssignmentId = "roleAssignmentIdGoesHere" #e.g. $roleAssignmentId = "/subscriptions/f8226644-2a08-4229-9ade-5e1e93e3dca3/providers/Microsoft.Authorization/RoleAssignments/b672efac-42bd-4377-908b-d573f81657e9"
$uri = "https://management.azure.com/$($roleAssignmentId)?api-version=2022-04-01"
$res = invoke-azrestmethod -uri $uri -method GET
($res.content | convertfrom-json) | convertto-json -depth 99
```
scenario2 seems that it was not created by PIM (expect: ObjectType: SP APP __EXT__)

**Comment by neok-g** [comment]
@JulianHayward The output for scenario 1 (role assignment cost management reader):

![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/72820eb6-d704-44a8-8cbd-ff9df527955d)

But your request does not contain any PIM details correct?

**Comment by neok-g** [comment]
Could you give an update?

**Comment by JulianHayward** [comment]
@neok-g unfortunately, currently I am not able to repro the issue. With regards to [issue217](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/issues/217) I would not invest troubleshooting this one further but keep it in backlog as test for the migration to the ARM APIs.
