### ISSUE TITLE
Which repo is leading?

### ISSUE THREAD

**Issue by neok-g** [JulianHayward/Azure-MG-Sub-Governance-Reporting#233]
**AzGovViz version**
6.4.5

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
It is not a bug but more a question about which repo is leading for AzGovViz or guidance which one I should use: initially and for syncing updates?

There seem to be 3:
https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting (this one) -> version 6.4.5
https://github.com/Azure/Azure-Governance-Visualizer/ (mirror of yours) -> version 6.4.3
https://github.com/Azure/Azure-Governance-Visualizer-Accelerator (accelerator) -> version 0.0.0

It is also not clear on which repo to log issues?

**Comment by JulianHayward** [comment]
* https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting (this one) -> version 6.4.5
Latest and greatest will be available here at first
* https://github.com/Azure/Azure-Governance-Visualizer/ (mirror of yours) -> version 6.4.3
Will sync the latest within a couple of days
* https://github.com/Azure/Azure-Governance-Visualizer-Accelerator (accelerator) -> version 0.0.0
This is the accelerator only
