### ISSUE TITLE
AzGovViz webapp/ app service extremely slow

### ISSUE THREAD

**Issue by neok-g** [JulianHayward/Azure-MG-Sub-Governance-Reporting#234]
**AzGovViz version**
6.4.5
 
**CodeRunPlatform**
Azure DevOps
 
**Describe the bug**
I used the bicep modules from the accelerator to create an AppService and App Service plan (with configured SKU/ runtime) and configured AzGovViz to publish the results to this webapp. However when loading the site it takes minutes to load the HTML file
 
**Screenshots**
 
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/3228810/ec32ec6b-d13d-4335-97f3-5da49e495962)

 
**Additional context**
- I enabled "Always on" on the App Service and increased the App Service Plan SKU to B3 instead of B1 without any effect.
- My html file is 43MB. DefinitionInsighs html is about 34MB.
- Tried this on Chrome/ Safari (MacOs) and Edge (Windows Server)

**Comment by JulianHayward** [comment]
most of the work happens on the client side.
Some options: try with a more performant PC, or try the -noScopeInsights parameter
