### ISSUE TITLE
Command 'ConvertFrom-Json -AsHashtable' failed. 

### ISSUE THREAD

**Issue by DahliaRane** [JulianHayward/Azure-MG-Sub-Governance-Reporting#236]
'Getting Private Endpoints for Subscription: -----------Command 'ConvertFrom-Json' failed: Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'Provisioner' was 'provisioner'.
[AzAPICall 1.2.1] 'Getting Private Endpoints for Subscription------------------Trying command 'ConvertFrom-Json -AsHashtable'

[AzAPICall 1.2.1] 'Getting Private Endpoints for Subscription--------------------Command 'ConvertFrom-Json -AsHashtable' succeeded. Please file an issue at the AzGovViz GitHub repository (aka.ms/AzGovViz) and provide a dump 

[AzAPICall 1.2.1] 'Getting Private Endpoints for Subscription-------------------Command 'ConvertFrom-Json -AsHashtable' failed. Please file an issue at the AzGovViz GitHub repository (aka.ms/AzGovViz) and provide a dump (scrub subscription Id and company identifyable names) of the resource (portal JSOn view) - Thank you!

**Comment by DahliaRane** [comment]
I could not find the key 'provisioner'/'Provisioner'  in any private end point for the subscription it failed.

**Comment by JulianHayward** [comment]
can you try this:

```pwsh
$subscriptionId = "subId" #example: fb66b6e2-879e-4e99-97a8-72c767d9bd75
$uri = "https://management.azure.com/subscriptions/$($subscriptionId)/providers/Microsoft.Network/privateEndpoints?api-version=2022-05-01"
$method = 'GET'
$res = Invoke-AzRestMethod -Uri $uri -Method $method
$resObj = ($res.Content | ConvertFrom-Json)
$resObjAsHashtable = ($res.Content | ConvertFrom-Json -AsHashtable)
```

**Comment by DahliaRane** [comment]
ConvertFrom-Json:
Line |
   6 |  $resObj = ($res.Content | ConvertFrom-Json)
     |                            ~~~~~~~~~~~~~~~~
     | Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'Provisioner' was 'provisioner'.
     
When I remove the line $resObj = ($res.Content | ConvertFrom-Json) it worked

**Comment by DahliaRane** [comment]
"tags": {
        "AppName": "*****",
        "CostCenter": "*****",
        "Environment": "dev",
        "Provisioner": "Terraform",
        "module_name": "private_endpoint",
        "module_version": "1.1.0",
        "provisioner": "Terraform",
        "test_tag": "Testing  Dev"
    },

**Comment by JulianHayward** [comment]
so, is the tagName with differing casing intended?

**Comment by DahliaRane** [comment]
I am not sure but seeing the values I think the two different cases are referring same value.

In some other private endpoints i don't see lower case "provisioner".

    "tags": {
        "AppName": "",
        "CostCenter": "",
        "Environment": "",
        "Provisioner": "Terraform",
        "UseCase": "Vault",
        "module_name": "private_endpoint",
        "module_version": "1.1.0"
    }

**Comment by JulianHayward** [comment]
I need to think about handling such scenarios with the azapicall/azgovviz.. not sure how common such scenario is, can you check with the team that deployed that PE with terraform?

**Comment by DahliaRane** [comment]
Its quite common . We have some subscriptions which has such scenarios.

**Comment by JulianHayward** [comment]
@DahliaRane sorry for the delay. In general, Azure resource JSON do not come with multicased keys. In your case the Tags are the problem / such issue has not been reported before (so I assume a rare edge case here).

**Comment by DahliaRane** [comment]
Ok looks like we cant delete keys which are multicased. Can you let me know where to modify the code or some solution for this rare edge case.

**Comment by JulianHayward** [comment]
give it a try using the parameter [-noNetwork](https://github.com/julianhayward/azure-mg-sub-governance-reporting?tab=readme-ov-file#parameters). 

Can you share some insights why you are using these multicased tagsNames?

**Comment by JulianHayward** [comment]
@DahliaRane any update from your side?

**Comment by cjtous1** [comment]
FYI, we've hit the same issue here. What would need to be modified within AzAPICall to support tag keys with different casing?
@JulianHayward
