### ISSUE TITLE
Login failed with Powershell when using OIDC. error: "Unexpected token R in JSON at position 0"

### ISSUE THREAD

**Issue by PieterbasNagengast** [JulianHayward/Azure-MG-Sub-Governance-Reporting#237]
**AzGovViz version**
v6.4.5

**CodeRunPlatform**
GitHub Actions - Azure/Login

**Describe the bug**
When using OIDC with GitHub Action the login fails with: "Unexpected token R in JSON at position 0".

**Screenshots**
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/63040880/dbdefb11-6af6-47d7-a5c3-7d6329e5516d)

**Additional context**
Please update the Github actions to use Azure/Loginv2 instead of v1.
Ref1: https://github.com/Azure/login/issues/447
Ref2: https://github.com/Azure/login/issues/447#issuecomment-2128494445

**Comment by JulianHayward** [comment]
@PieterbasNagengast thanks, will be updated with the upcoming release.

**Comment by JulianHayward** [comment]
dito
