### ISSUE TITLE
throwing - Command ConvertFrom-Json -AsHashtable failed (*different casing*)

### ISSUE THREAD

**Issue by sanjayraist** [JulianHayward/Azure-MG-Sub-Governance-Reporting#240]
I am getting below exception message at line 5983 of script AzGovVizParallel.ps1

Exception: C:\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:5983
Line |
5983 |          $subsToProcessInCustomDataCollectionBatch | ForEach-Object -P …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | throwing - Command ConvertFrom-Json -AsHashtable failed (*different casing*)

Any idea? Thanks for your support

**Comment by JulianHayward** [comment]
@sanjayraist please share the information as requested when you open an issue. There should also be some more information what it was processing at throw.

**Comment by sanjayraist** [comment]
Hi Julian,
Will update short , was struck in another issue.
This is important issue for me.



ST Restricted

**Comment by JulianHayward** [comment]
please reopen if needed.
