### ISSUE TITLE
[Error] Cannot run AzGovViz using the user's Access Token

### ISSUE THREAD

**Issue by skhomyuk** [JulianHayward/Azure-MG-Sub-Governance-Reporting#243]
**AzGovViz version**
6.4.5

**CodeRunPlatform**
Console

**Describe the bug**
I am trying to implement the service/console app to run AzGovViz under different users using their access tokens. This application expects the user's access token as one of parameters and run AzGovViz, no any interactivity with user. A valid access token is prepared by another application. AzGovViz starts to work but get the error below. 

_Steps to reproduce:_
1. Connect-AzAccount -AccessToken $accessToken -TenantId $tenantId -AccountId $accountId -SubscriptionId $subscriptionId
2. .\AzGovVizParallel.ps1 -ManagementGroupId $managementGroupId  -OutputPath $outputPath

_Please note, on application side no any pre-stored user's context in the cache. If you already have connected user, it needs to clear the cache before (run clear-AzContext) to reproduce the issue._

**Error**
Check Subscription: 'Subscription replaced' (criteria: quotaId notLike 'AAD*'; state==enabled)
 +Processing new bearer token request 'ARM' "https://management.azure.com"
Likely your Azure credentials have not been set up or have expired, please run 'Connect-AzAccount -tenantId <tenantId>'
Write-Error: C:\Users\Folder\Documents\PowerShell\Modules\AzAPICall\1.2.2\functions\AzAPICallFunctions.ps1:1654
Line |
1654 |  …             Logging -logMessage "-ERROR processing new bearer token r …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | -ERROR processing new bearer token request (Console) for targetEndPoint 'ARM' (https://management.azure.com):
     | Exception calling "Authenticate" with "7" argument(s): "[AccessTokenAuthenticator] failed to retrieve access
     | token for resource 'https://management.azure.com';. Please ensure that you have provided the appropriate access
     | tokens when using access token login."
Exception: C:\Users\Folder\Documents\PowerShell\Modules\AzAPICall\1.2.2\functions\AzAPICallFunctions.ps1:1655
Line |
1655 |  …             Throw 'Error - check the last console output for details' …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Screenshots**
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/31669355/9907b41c-94aa-4a24-9104-84a2f40c3f25)
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/31669355/d07b2838-aa91-405f-9408-71464bcdd4bd)

**Additional context**
It seems the error is appeared in _AzAPICall createBearerToken_ function. Instance.AuthenticationFactory.Authenticate does not work in case azContext is created using user's access token.

**Comment by JulianHayward** [comment]
@skhomyuk interesting scenario.. when you say 'user' are these really accounts of type 'user'? is there no way to use Service Principal? 
AzDO/GitHub is not an option?

**Comment by skhomyuk** [comment]
Hi @JulianHayward, I think the account type in this case is _'AccessToken'_, like it is shown on the second screen above.
It is should be multi-tenant application with user-specific permissions. If think about Service Principal way, in this case **"Applications permissions"** is only documented, but what about **"Delegated permissions"**? The service principal with delegated permissions is also going to use user's _Access Token_, and it looks like is no option to run _AzGovViz_ too.
I think, I just need your confirmation that AzGovViz does not support 'AccessToken' account type now.

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup/azure-devops.md
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/31669355/7a077b1d-c944-44a4-9a13-1e1c0476877a)


I need to use **"Delegated permissions"**:
![image](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/31669355/59e8a1bd-0d9d-459a-b137-258070621cb5)

**Comment by JulianHayward** [comment]
jepp, does not work that way :(. Please share your workaround later on. thx
