### ISSUE TITLE
Azure China issue: The resource type 'pricings' could not be found in the namespace 'Microsoft.Security'

### ISSUE THREAD

**Issue by cajohanikea** [JulianHayward/Azure-MG-Sub-Governance-Reporting#244]
**AzGovViz version**
6.4.4

**CodeRunPlatform**
GitHub Action

**Describe the bug**
After the api version change to 2024-01-01 for microsoft.security an error is raised for Azure China:
_(StatusCode: '404' (NotFound)) <.code: ''> <.error.code: 'InvalidResourceType'> | <.message: ''> <.error.message: 'The resource type 'pricings' could not be found in the namespace 'Microsoft.Security' for api version '2024-01-01'. The supported api-versions are '2023-01-01,2022-03-01,2018-06-01,2017-08-01-preview'.'>  - unhandledErrorAction: Stop_

**Comment by JulianHayward** [comment]
@cajohanikea thanks for reporting. Can you check the [dev branch](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/developmentJH) this should fix the issue. See that last var `APIMappingCloudEnvironment ` in the [param block](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/5fa4361e09e89606fb0bb401d313747a8e4f8b03/pwsh/AzGovVizParallel.ps1#L632)

**Comment by cajohanikea** [comment]
@JulianHayward That looks really good!

**Comment by JulianHayward** [comment]
great - closing
