### ISSUE TITLE
Allow to filter by subscriptionIds

### ISSUE THREAD

**Issue by skhomyuk** [JulianHayward/Azure-MG-Sub-Governance-Reporting#245]
Hello, thank you for the script.
We need to collect the data for specific subscriptions only in the management group. Unfortunately, parameter `SubscriptionQuotaIdWhitelist` does not work for our case.

May you improve the script to be able to filter on subscriptions by id?

**Comment by JulianHayward** [comment]
@skhomyuk thanks for the request. Please clarify the problem you are facing / why you need to filter to specific subscription Ids.

If you want to give it a try:
The list of subscriptions to process (`$subsToProcessInCustomDataCollection`) are generated in https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/pwsh/dev/functions/detailSubscriptions.ps1

Mind the [contribution guide](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/contributionGuide.md)

**Comment by JulianHayward** [comment]
closing for now
