### ISSUE TITLE
The type eq 'subscription' or type eq 'managementgroup' filter is invalid.'

### ISSUE THREAD

**Issue by DevanshuSyk** [JulianHayward/Azure-MG-Sub-Governance-Reporting#254]
!f97434b8 Please report at aka.ms/AzGovViz and provide the following dump
[AzAPICallErrorHandler 1.2.1] Get PIM onboarded Subscriptions and Management Groups try #1; uri:"https://graph.microsoft.com/beta/privilegedAccess/azureResources/resources?$select=id%2cdisplayName%2ctype%2cexternalId&$expand=parent&$filter=(type+eq+%27subscription%27+or+type+eq+%27managementgroup%27)&$skiptoken=sCNNyBAi906cc1zn_P-HEw"; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidFilter'> | <.message: ''> <.error.message: 'The type eq 'subscription' or type eq 'managementgroup' filter is invalid.'> - (plain : @{error=}) - AzAPICall: Stop
Parameters:
accountType:ServicePrincipal
ARMLocations:australiacentral australiacentral2 australiaeast australiasoutheast brazilsouth brazilsoutheast brazilus canadacentral canadaeast centralindia centralus centraluseuap eastasia eastus eastus2 eastus2euap eastusstg francecentral francesouth germanynorth germanywestcentral israelcentral italynorth japaneast japanwest jioindiacentral jioindiawest koreacentral koreasouth mexicocentral northcentralus northeurope norwayeast norwaywest polandcentral qatarcentral southafricanorth southafricawest southcentralus southcentralusstg southeastasia southindia spaincentral swedencentral switzerlandnorth switzerlandwest uaecentral uaenorth uksouth ukwest westcentralus westeurope westindia westus westus2 westus3
azAccountsVersion:2.16.0
azAPICallModuleVersion:1.2.1
azureCloudEnvironment:AzureCloud
codeRunPlatform:Console
debugAzAPICall:False
debugWriteMethod:Host
DoAzureConsumption:True
DoAzureConsumptionPreviousMonth:False
DoNotIncludeResourceGroupsAndResourcesOnRBAC:False
DoNotIncludeResourceGroupsOnPolicy:False
DoNotShowRoleAssignmentsUserData:False
DoPSRule:False
GitHubActionsOIDC:False
gitHubRepository:aka.ms/AzGovViz
HierarchyMapOnly:False
LargeTenant:False
ManagementGroupsOnly:False
NoALZPolicyVersionChecker:False
NoJsonExport:True
NoMDfCSecureScore:False
NoNetwork:False
NoPolicyComplianceStates:False
NoResourceProvidersAtAll:False
NoResourceProvidersDetailed:False
NoResources:False
NoStorageAccountAccessAnalysis:True
onAzureDevOps:False
onAzureDevOpsOrGitHubActions:False
onGitHubActions:False
PolicyAtScopeOnly:False
ProductVersion:6.4.5
PSRuleFailedOnly:False
psVersion:7.4.4
RBACAtScopeOnly:False
skipAzContextSubscriptionValidation:False
subscriptionId4AzContext:undefined
subscriptionQuotaId:EnterpriseAgreement_2014-09-01
tenantId4AzContext:undefined
ThrottleLimit:10
userType:n/a
writeMethod:Host
[AzAPICallErrorHandler 1.2.1] Get PIM onboarded Subscriptions and Management Groups try #1; uri:"https://graph.microsoft.com/beta/privilegedAccess/azureResources/resources?$select=id%2cdisplayName%2ctype%2cexternalId&$expand=parent&$filter=(type+eq+%27subscription%27+or+type+eq+%27managementgroup%27)&$skiptoken=sCNNyBAi906cc1zn_P-HEw"; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidFilter'> | <.message: ''> <.error.message: 'The type eq 'subscription' or type eq 'managementgroup' filter is invalid.'>  - unhandledErrorAction: Stop
Exception: 
Line |
 778 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
@DevanshuSyk please see https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/issues/217
