### ISSUE TITLE
Export-Csv calls - remove the double quotes

### ISSUE THREAD

**Issue by pjjohnson** [JulianHayward/Azure-MG-Sub-Governance-Reporting#26]
When calling Export-Csv, it defaults to add double quotes to each cell, and this creates problems when using it as a data source in PowerBI.  

Adding the parameter ""-UseQuotes AsNeeded" to the 2 Export-Csv calls will remove adding the double quotes, and then the resulting CSV is easily used in PowerBI.

**Comment by JulianHayward** [comment]
please check new parameter `-CsvExportUseQuotesAsNeeded`

**Comment by JulianHayward** [comment]
closed
