### ISSUE TITLE
Publishing to Wiki fails

### ISSUE THREAD

**Issue by smdotai** [JulianHayward/Azure-MG-Sub-Governance-Reporting#262]
**AzGovViz version**
Azure Governance Visualizer v6_major_20231113_1

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
Publishing to Wiki fails to render HTLM Subscriptions or JSON

**Screenshots**
![image](https://github.com/user-attachments/assets/b05becf1-4a29-4b79-a191-04429dfabbb9)

![image](https://github.com/user-attachments/assets/5facdef5-c728-453c-8c0d-6d6a159f02e4)

![image](https://github.com/user-attachments/assets/e87f27a2-6cb8-4b74-b6d1-ccc1d04dce50)

**Additional context**
I've tried modifying parameters for LargeTenant, as well as setting to not include inheriting, but the issue prevails. Is this a known bug?

**Comment by JulianHayward** [comment]
hi @smdotai the wiki only renders markdown. Maybe we could place the markdown with the mermaid tree into a dedicated folder. Hope that clarifies.

**Comment by JulianHayward** [comment]
@smdotai yes, all else is not markdown but html/csv/json

**Comment by smdotai** [comment]
I see the problem. The file is 33MB and the max allowable file size is 20MB. Any LPTs on how to cut it down?

**Comment by JulianHayward** [comment]
mate, the wiki will not render the html files.

**Comment by smdotai** [comment]
Thanks for being direct. I see what you're saying now... Sorry for the confusion and I appreciate your time. Not a bug, end user error aka PEBKAC. :) 

Love the project and thank you for developing it
