### ISSUE TITLE
Large Tenant run stops at Private Endpoints due to ConvertFrom-Json

### ISSUE THREAD

**Issue by Azdamus** [JulianHayward/Azure-MG-Sub-Governance-Reporting#267]
**AzGovViz version**
Version 6.6.1

**CodeRunPlatform**
Windows 11 Laptop - PowerShell 7.3.6 - VSCode (latest)

**Describe the bug**
Tool completely stops mid run with error below on a large tenant with well over 500 subscriptions. This however does not occur on a smaller tenant.

`[AzAPICall 1.2.4] 'Getting Private Endpoints for Subscription: 'a1a-51159-dev-test-sub-qps-02' ('2962bd46-3ef4-4b6f-bc37-f9373d537e6e') [quotaId:'EnterpriseAgreement_2014-09-01']' uri='https://management.azure.com/subscriptions/redacted/providers/Microsoft.Network/privateEndpoints?api-version=2022-05-01' Command 'ConvertFrom-Json -AsHashtable' failed. Please file an issue at the AzGovViz GitHub repository (aka.ms/AzGovViz) and provide a dump (scrub subscription Id and company identifyable names) of the resource (portal JSOn view) - Thank you!
Exception: C:\Users\redacted\Documents\GitHub_Repo\Azure-MG-Sub-Governance-Reporting\pwsh\AzGovVizParallel.ps1:6613:9
Line |
6613 |          $subsToProcessInCustomDataCollectionBatch | ForEach-Object -P …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | throwing - Command ConvertFrom-Json -AsHashtable failed (*different casing*)
PS C:\Users\redacted\Documents\GitHub_Repo\Azure-MG-Sub-Governance-Reporting>`

**Screenshots**
![error-govwiz](https://github.com/user-attachments/assets/746759f1-9541-4966-a5c6-ad4fc062efc2)

**Additional context**
I tried replicating the issue in a small tenant with only one private endpoint. I did not get the error, so I am still investigating the Root Cause.

Command run syntax:
.\pwsh\AzGovVizParallel.ps1 -ManagementGroupId 'tenant_id_here' -NoResourceProvidersDetailed -NoMDfCSecureScore -NoPolicyComplianceStates -NoResourceDiagnosticsPolicyLifecycle -NoAADGroupsResolveMembers -NoPIMEligibility $True -LargeTenant -ThrottleLimit 20 -StatsOptOut -ShowMemoryUsage -OutputPath "C:\Users\redacted\Documents\Outputs\AzGovResult"

**Comment by JulianHayward** [comment]
please see:
https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/issues/236
or https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/issues/235

**Comment by Azdamus** [comment]
#236 - is the same scenario indeed. It seems we have tags that are not consistent. Problem is that correcting the tags in an environment with over 500 subscriptions and 15k resources is not really something that is done fast due to procedures and regulations. 
I tried running it with -NoCSVExport and -NoNetwork for now and it finished successfully, I think a -NoTags option would go a long way because most large tenants have a lot of tags and inevitable the casing will have typos. 

Will close this since it's a known issue. Thank you for your help and this great tool!
