### ISSUE TITLE
Context is not set to any Subscription

### ISSUE THREAD

**Issue by thecomalley** [JulianHayward/Azure-MG-Sub-Governance-Reporting#31]
Getting `Context is not set to any Subscription` error from Azure Pipelines scheduled run. However manually re-running the Pipeline often causes it to succeed, working fine prior to v5 upgrade.

AzGovVizVersion = v5_major_20210308_3

` Context test failed: Context is not set to any Subscription. Set your context to a subscription by running: Set-AzContext -subscription <subscriptionId> (run Get-AzSubscription to get the list of available Subscriptions). When done re-run AzGovViz`

**Comment by JulianHayward** [comment]
does this always happen when running der pipeline from schedule?
We could be pragmatic and add a parameter for default subscription to set context. Any thoughts?

**Comment by JulianHayward** [comment]
@thecomalley

**Comment by thecomalley** [comment]
not only, manual trigger just now failed, follow up manual run succeeded

**Comment by JulianHayward** [comment]
@thecomalley please check dev_31 branch, new parameter: 'SubscriptionId4AzContext'

`.\AzGovVizParallel.ps1 -ManagementGroupId <your-Management-Group-Id> -SubscriptionId4AzContext <yourSubscriptionId>`
