### ISSUE TITLE
Dos it support AzureChinaCloud ? I got an error message when I process on AzureChinaCloud account

### ISSUE THREAD

**Issue by angerfirecn** [JulianHayward/Azure-MG-Sub-Governance-Reporting#32]
Checking AAD UserType
 Checking AAD UserType - try #1; returned: <.code: ''> <.error.code: 'Authorization_RequestDenied'> | <.message: ''> <.error.message: 'Insufficient privileges to complete the operation.'> - (plain : @{error=}) investigate that error!/exit
Exception: D:\Tools\1.ps1:661
Line |
 661 |  …             Throw "Error - check the last console output for details" …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
@angerfirecn 
it should work in AzureChinaCloud, yes.
Can you please provide more information - are you running the script as user that is a **member** or **guest**?
Not sure if this actually works but can you please test https://developer.microsoft.com/en-us/graph/graph-explorer using `https://microsoftgraph.chinacloudapi.cn/v1.0/me?$select=userType`

**Comment by JulianHayward** [comment]
close /14days
