### ISSUE TITLE
ParserError: /home/----/AzGovVizParallel.ps1:216

### ISSUE THREAD

**Issue by cjnova** [JulianHayward/Azure-MG-Sub-Governance-Reporting#37]
Using latest version I got this error:

ParserError: /home/----/AzGovVizParallel.ps1:216
Line |
 216 |  … ata-ga-click="(Logged out) Header, go to Features">Features <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.

pwsh version 7.1.3

**Comment by JulianHayward** [comment]
did you copy/paste the code or clone?
`Checking powershell edition and version
 PS check passed : (Major[7]; Minor[1] gt 0); (minimum supported version '7.0.3')
 PS Edition: Core
 PS Version: 7.1.3`

**Comment by cjnova** [comment]
I tried to run it from Azure console (Bash & Powershell). From the console I used 'wget' to download the powershell file. Also tried on my local device with all Az modules installed with same output.

**Comment by cjnova** [comment]
My fault. I checked powershell file and the content is not right. Maybe a download error. Closing the issue. Thanks
