### ISSUE TITLE
failed pipeline due to unsupported subscription offer

### ISSUE THREAD

**Issue by thefeds-nau** [JulianHayward/Azure-MG-Sub-Governance-Reporting#38]
Hello,
We have an issue while using this. We have several student subscriptions in our tenant, and when trying to run the pipeline i get this.

Current AzContext OK: NAU Initial Subscription; 9a0b8e1e-fa67-496f-894d-cffe55d90d07; QuotaId: EnterpriseAgreement_2014-09-01
Getting Consumption data for scope: '***' for period 1 days (2021-06-24 - 2021-06-24)
 Getting Consumption data for scope: '***' for period 1 days (2021-06-24 - 2021-06-24) - try #1; returned: <.code: ''> <.error.code: 'BadRequest'> | <.message: ''> <.error.message: 'Cost management data is unavailable for subscription b1739bfa-c40b-438b-becf-012f32ac9e41. The offer MS-AZR-0170P is not supported. (Request ID: c7ad409d-dc9b-4eaa-a3d0-f101bf95b5d1)'> - (plain : @{error=}) investigate that error!/exit
AzAPICall: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:18719
 Line |
18719 |  … ptionData = AzAPICall -uri $uri -method $method -body $body -currentT …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error

##[error]PowerShell exited with code '1'.

**Comment by JulianHayward** [comment]
thanks for reporting, meanwhile you may work around that error using one of the following options:
* parameter `-NoAzureConsumption`
* parameter `-SubscriptionQuotaIdWhitelist "AzureForStudents_"`

**Comment by thefeds-nau** [comment]
Thank you, but where would I set this?

Fed Gallardo
Systems Administrator, Senior - SPF
Information Technology Services
Northern Arizona University
928.523.2963

**Comment by thefeds-nau** [comment]
Getting all Subscriptions duration: 0.0771292 seconds
Current AzContext OK: NAU Initial Subscription; 9a0b8e1e-fa67-496f-894d-cffe55d90d07; QuotaId: EnterpriseAgreement_2014-09-01
Getting Consumption data for 0 Subscriptions (QuotaId Whitelist (Azure); state:enabled) for period 1 days (2021-06-24 - 2021-06-24)
 Getting Consumption data for 0 Subscriptions (QuotaId Whitelist (Azure); state:enabled) for period 1 days (2021-06-24 - 2021-06-24) - try #1; returned: <.code: ''> <.error.code: 'BadRequest'> | <.message: ''> <.error.message: 'Cost management data is unavailable for subscription b1739bfa-c40b-438b-becf-012f32ac9e41. The offer MS-AZR-0170P is not supported. (Request ID: 62e6e2bb-6a4a-49ca-84a7-c341baa13aca)'> - (plain : @{error=}) investigate that error!/exit
AzAPICall: /home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1:18719
 Line |
18719 |  … ptionData = AzAPICall -uri $uri -method $method -body $body -currentT …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error

##[error]PowerShell exited with code '1'.

**Comment by thefeds-nau** [comment]
Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
AzGovVizParallel.ps1: /home/vsts/work/_temp/b6de6598-7bee-4adf-bc81-8a24cd061a8c.ps1:4
Line |
   4 |  … iter ";" -AzureDevOpsWikiAsCode -SubscriptionQuotaIdWhitelist -Subscr …
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Missing an argument for parameter
     | 'SubscriptionQuotaIdWhitelist'. Specify a parameter of type
     | 'System.Array' and try again.

##[error]PowerShell exited with code '1'.

**Comment by thefeds-nau** [comment]
better yet, is there a way to ignore disable subscriptions?

**Comment by thefeds-nau** [comment]
disregard, i added -NoAzureConsumption and it is working
