### ISSUE TITLE
Publish AzGovViz output on MS Teams

### ISSUE THREAD

**Issue by TimWanierke** [JulianHayward/Azure-MG-Sub-Governance-Reporting#4]
Is it possible to publish the output of this script on MS Teams as well in the future?

**Comment by JulianHayward** [comment]
Hey Tim,

You can vote for this feature here https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35792950-add-azure-devops-vsts-wiki-tab-to-the-teams-connec

As a workaround in Teams you can add a Tab and select the 'website' app then enter the URL to your wiki
![image](https://user-images.githubusercontent.com/45695032/77588110-7ce46680-6ee9-11ea-8f5e-50f0bc5fe241.png)
