### ISSUE TITLE
Add-Content failing due to .html in use by another process

### ISSUE THREAD

**Issue by jdemaree** [JulianHayward/Azure-MG-Sub-Governance-Reporting#43]
Looks like it's not handling the multi-thread write to the html file smoothly.

The resulting output has the hierarchy diagram but no details. 

![image](https://user-images.githubusercontent.com/49085407/126395560-0d40e36d-21a2-44fc-8bca-d059f997d045.png)

**Error with Redactions**
![image](https://user-images.githubusercontent.com/49085407/126395306-ce912756-1afd-4654-a323-82918fe08071.png)

**Comment by JulianHayward** [comment]
is this a OneDrive synced directory?

**Comment by jdemaree** [comment]
Ah... Yes.  Yes, it is.   Flipping it to a local folder.
