### ISSUE TITLE
Hangs when using Tenant root group

### ISSUE THREAD

**Issue by ryansmyth2001** [JulianHayward/Azure-MG-Sub-Governance-Reporting#5]
Tried to run this tool on our tenant root group and it just hangs - killed it after 8 hours. 
Used the AAD tenant ID as the mgmt group ID.

Should this work on tenant root group?
Does work on lower level mgmt groups.

**Comment by ryansmyth2001** [comment]
Sorry I think it might be I dont have read access to the root mgmt group..will test again.

**Comment by alexisP** [comment]
I confirm that I do not have issue to play it on the tenant root group.
