### ISSUE TITLE
Getting Consumption data (scope Sub NAU DBA Online Subscription 'Removed for Online' (EnterpriseAgreement_2014-09-01))

### ISSUE THREAD

**Issue by thefeds-nau** [JulianHayward/Azure-MG-Sub-Governance-Reporting#54]
Hello Julian,
Received this error below trying to run the PowerShell command against our tenant.

!Please report at aka.ms/AzGovViz and provide the following dump
  Getting Consumption data (scope Sub NAU DBA Online Subscription 'Removed for Online' (EnterpriseAgreement_2014-09-01)) - try #1; returned: (StatusCode: '') <.code: ''> <.error.code: 'NotFound'> | <.message: ''> <.error.message: 'Cost management data is not supported for subscription(s) "Removed for Online" in the provided api-version. Please use api-version 2019-10-01 or later. (Request ID: cdd84ec7-e0d5-4bd1-99e6-632870d34630)'> - (plain : @{error=}) - EXIT
Exception: C:\Scripts\AzGovViz\AzGovVizParallel.ps1:19735
 Line |
19735 |  …             $subsToProcessInCustomDataCollection | ForEach-Object -Pa …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Error - AzGovViz: check the last console output for details

**Comment by JulianHayward** [comment]
Can you please try the following: 
1. try with apiVersion = 2019-10-01
2. force return of available API version by using apiVersion = 0000-00-00

```
$subId = "<subId>"
$apiVersion = "2019-11-01"
#$apiVersion = "0000-00-00"
$path = "/subscriptions/$($subId)/providers/Microsoft.CostManagement/query?api-version=$($apiVersion)"
$azureConsumptionStartDate = "2021-08-31"
$azureConsumptionEndDate = "2021-08-31"
$body = @"
{
    "type": "ActualCost",
    "dataset": {
        "granularity": "none",
        "aggregation": {
            "totalCost": {
                "name": "PreTaxCost",
                "function": "Sum"
            }
        },
        "grouping": [
            {
                "type": "Dimension",
                "name": "SubscriptionId"
            },
            {
                "type": "Dimension",
                "name": "ResourceId"
            },
            {
                "type": "Dimension",
                "name": "ConsumedService"
            },
            {
                "type": "Dimension",
                "name": "MeterCategory"
            },
            {
                "type": "Dimension",
                "name": "ChargeType"
            }
        ]
    },
    "timeframe": "Custom",
    "timeperiod": {
        "from": "$($azureConsumptionStartDate)",
        "to": "$($azureConsumptionEndDate)"
    }
}
"@  

$ret = Invoke-AzRestMethod -Method "POST" -Path $path -Payload $body
$ret
```

**Comment by thefeds-nau** [comment]
I'm sorry. i dont know what you mean.

**Comment by JulianHayward** [comment]
fixed: v5_major_20210901_1

**Comment by JulianHayward** [comment]
demo-output moved to sperate repository (https://github.com/JulianHayward/AzGovViz), issue resolved - I guess
