### ISSUE TITLE
Exception encountered.

### ISSUE THREAD

**Issue by PhilWheat** [JulianHayward/Azure-MG-Sub-Governance-Reporting#60]
Learning the project, but got this on my test Tenant and am following directions.  Could easily be PEBKAC.

 Building TenantSummary
  processing (pre) TenantSummary RoleAssignments (all 5)
   RelatedPolicyAssignmentsAll duration: 6.562E-05 minutes (0.0039372 seconds)
   Processing unresoved Identities (createdBy)
    1 unresolved identities that created a RBAC Role assignment (createdBy)
    0 unresolved identities that have a value
    IdentitiesToCheck: ""
- - - - - - - - - - - - - - - - - - - -
!Please report at aka.ms/AzGovViz and provide the following dump
    resolveObjectbyId RoleAssignment - try #1; returned: (StatusCode: '') <.code: ''> <.error.code: 'Request_BadRequest'> | <.message: ''> <.error.message: 'Invalid GUID:'> - (plain : @{error=}) - EXIT

**Comment by JulianHayward** [comment]
thanks for reporting, please try the latest release

**Comment by PhilWheat** [comment]
No exception with the latest.  Thanks!
