### ISSUE TITLE
CustomDataCollection ManagementGroups getRoleAssignments CustomDataCollection Mg /providers/Microsoft.Management/managementGroups/xxx-xxx-xxx-xxx #7 'Unexpected Error' occurred 'Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.' - Please report this error/exit Exception: AzGovVizParallel.ps1:1767:5

### ISSUE THREAD

**Issue by nietakipawel** [JulianHayward/Azure-MG-Sub-Governance-Reporting#62]
Hi there,
first of all thanks for AzGov, I am wondering if you have a chance to execute it towards Az China Cloud. I am facing some issues once trying to execute it using SPN with all the Reader rights (Application) on the MS Graph and Azure level.
Any idea what might be a reason here and how to move forward? thanks much

CustomDataCollection ManagementGroups
getRoleAssignments CustomDataCollection Mg /providers/Microsoft.Management/managementGroups/xxx-xxx-xxx-xxx #7 'Unexpected Error' occurred 'Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.' - Please report this error/exit
Exception: AzGovVizParallel.ps1:1767:5

**Comment by JulianHayward** [comment]
hi there, it looks like you are missing the 'Azure Active Directory API' (not 'Microsoft Graph') permission: Directory / Read.All
Can you confirm you have set all required permissions?

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#required-permissions-in-azure-active-directory

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup.md#grant-permissions-in-aad---option-1---api-permissions

**Comment by JulianHayward** [comment]
hi Pawel - I guess :)
currently a version that will not rely on the legacy 'Azure Active Directory API' (leveraged by get-azRoleAssigment cmdlet) is under development. If you are open for early bird testing, then please ping me on LinkedIn.

**Comment by nietakipawel** [comment]
thank you
