### ISSUE TITLE
Azure Active Directory API Read Permission Deprecated

### ISSUE THREAD

**Issue by sebastianrogers** [JulianHayward/Azure-MG-Sub-Governance-Reporting#63]
Permissions test failed: Your AzDO ServiceConnection seems to
     | lack 'Azure Active Directory API' Read permissions. Please
     | check the documentation:

However when I try and grant this I get the warning:

Azure Active Directory Graph will be deprecated in June 2022. We recommend using Microsoft Graph APIs for your application. If you are currently using Azure Active Directory Graph, please migrate to Microsoft Graph.

Have I misunderstood which permission I should be granting?

**Comment by JulianHayward** [comment]
please go for version 6 of AzGovViz: https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/tree/v6_major_20211011_1 with this version no access to 'Azure Active Directory Graph' API will be required.
The 'Azure Active Directory Graph' API endpoint seems to have been locked down only recently.
