### ISSUE TITLE
returned: (StatusCode: '') '429' | 'Too many requests. Please retry after 60 seconds

### ISSUE THREAD

**Issue by Tsholofelom** [JulianHayward/Azure-MG-Sub-Governance-Reporting#68]
Hello 
We have 260 subscriptions, I get error "returned: (StatusCode: '') '429' | 'Too many requests. Please retry after 60 seconds." when running script at the tenant root level

**Comment by JulianHayward** [comment]
interesting. Please share more details / script output before the error occurs

**Comment by JulianHayward** [comment]
@Tsholofelom can you please update?

**Comment by Tsholofelom** [comment]
Hi Julian 
The error resolved after I added the "NoAzureConsumption" argument in line 108 
It kept trying to get consumption data and then timing out
Thank you
