### ISSUE TITLE
Error in Pipeline Run - Powershell git clone 

### ISSUE THREAD

**Issue by heuristik1** [JulianHayward/Azure-MG-Sub-Governance-Reporting#7]
##[debug]system.culture=en-US
##[debug]errorActionPreference=stop
##[debug]failOnStderr=false
##[debug]ignoreLASTEXITCODE=false
##[debug]workingDirectory=/home/vsts/work/1/s
##[debug]check path : /home/vsts/work/1/s
##[debug]targetType=inline
##[debug]script=mkdir /home/vsts/wiki
cd /home/vsts/wiki
$TeamProjectUriFormat = [uri]::EscapeDataString("sfes")
git clone -c http.extraheader="AUTHORIZATION: bearer ***" https://dev.azure.com/<hidden>/$TeamProjectUriFormat/_git/wikiRepo
...
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/9358e2e0-ba52-4b95-a970-a04db5d7b54b.ps1'
Cloning into 'wikiRepo'...
remote: TF401019: The Git repository with name or identifier wikiRepo does not exist or you do not have permissions for the operation you are attempting.
fatal: repository 'https://dev.azure.com/<hidden>/sfes/_git/wikiRepo/' not found
install Az.ResourceGraph
##[debug]$LASTEXITCODE: 128

The wikiRepo Git does, in fact, exist.  The build service has full permissions to both repos.  Interestingly, the logs mistakenly add an extraneous ' to the end of the URL for the wikiRepo git.  But I don't know if this is related....

**Comment by JulianHayward** [comment]
also discovered that.
Still under investigation but findings so far: existing setup still working, whilst new setup runs into the error you are referencing.

As an immediate workaround you may use the just now published AzGovVizFix.yml. The output will now be pushed back to the repo hosting the code into folder 'wiki'.

**Comment by heuristik1** [comment]
Workaround successful!

**Comment by heuristik1** [comment]
https://blog.tylerdoerksen.ca/posts/2019/12/Azure-DevOps-Auth-Failures.html

This might have something to do with it?

**Comment by JulianHayward** [comment]
the issue seemed to have started occurring somewhen around early July 2020.

**Comment by heuristik1** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

Might have to declare both repos?

**Comment by JulianHayward** [comment]
looks promising! Do you want to discuss pros/cons using multiple vs single repository approach? ping me on LinkedIn
