### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by bagelsandcoffee** [JulianHayward/Azure-MG-Sub-Governance-Reporting#75]
Hello ,

This is not an issue but more of an query .Is it possible for you to point out at what point the HTML Is pulling code  for  "LinkedIn" and Github profile icon/link on top left hand corner? I would like to have it more streamlined with external links.

Thankx
Bagelcoffee

**Comment by JulianHayward** [comment]
hi @bagelsandcoffee 
can you please elaborate - do you want to remove those links or add some more links? happy to discuss options.. ping me on LinkedIn.

**Comment by JulianHayward** [comment]
taken offline
