### ISSUE TITLE
Azure DevOps pipeline does not work on self hosted VM Scale Set

### ISSUE THREAD

**Issue by Rsimk** [JulianHayward/Azure-MG-Sub-Governance-Reporting#79]
I tried to run ADO pipeline using self hosted agent pool with VM Scale Set. The only change I made to yaml file was agent pool name.
Pipeline failed on " Prerequisites check" step. Error message: 
"##[error]Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable."
VM Scale Set profile using Ubuntu server with 18_04-lts-gen2 plan.

**Comment by JulianHayward** [comment]
it looks like PowerShell 7 is not present?

**Comment by JulianHayward** [comment]
@Rsimk please update

**Comment by JulianHayward** [comment]
closed; no response
