### ISSUE TITLE
Exclude management group

### ISSUE THREAD

**Issue by bubbletroubles** [JulianHayward/Azure-MG-Sub-Governance-Reporting#82]
Not sure if this is an issue or just how to use the script, but is there any way to exclude a management group from the report?

In our tenant there is a management group for "Visual Studio Subscriptions" which are self-managed by developers (its their visual studio subscriber benefit subscriptions). Some of the things they do in there cause AzGovViz to fail (e.g. they don't register microsoft.insights, which stops the diagnostic log check from working). 

Ideally we would report from the top management group down, excluding the "Visual Studio Subscriptions" MG.

**Comment by JulianHayward** [comment]
right now you cannot exclude Management Groups, however you can use a Subscription whitelist based on quotaId - check the parameter `-SubscriptionQuotaIdWhitelist`  
example:  `.\AzGovVizParallel.ps1 -SubscriptionQuotaIdWhitelist 'MSDN_'`  
[AzGovViz parameters](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#parameters)  
[azure-offers](https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/understand-cost-mgt-data#supported-microsoft-azure-offers)

**Comment by JulianHayward** [comment]
one more you could run with parameter `-NoResources` first / helps you determine the variety of offers in your tenant..

**Comment by bubbletroubles** [comment]
Thanks - that will work for us!

**Comment by bubbletroubles** [comment]
Just checking the Quota ID, there are several offers with the same QuotaID

e.g.

EA Enterprise Dev/Test (MS-AZR-0148P)= MSDNDevTest_2014-09-01	
Visual Studio (	MS-AZR-0060P) = MSDNDevTest_2014-09-01	

Is there any way to filter on the Offer ID's (e.g. MS-AZR-0148P)?

**Comment by JulianHayward** [comment]
to my knowledge we cannot get the offerId programmatically. I´d like to better understand your scenario / eval the options to get this going, please connect with me on LinkedIn then we can arrange for a discussion next week.

**Comment by JulianHayward** [comment]
@bubbletroubles please update

**Comment by bubbletroubles** [comment]
We did manage to find a offerID filter that excludes the visual studio subs, but some may fall through the cracks in future. Our immediate issue is closed, but it would be good to exclude all subs in a management group as a future enhancement. 

Also thanks for developing azgovviz - it's an awesome tool.
