### ISSUE TITLE
Feature Request: Adding User Setting data

### ISSUE THREAD

**Issue by wayneme75** [JulianHayward/Azure-MG-Sub-Governance-Reporting#83]
Should we be calling out app reg, admin portal and LinkedIn account connections into the Active Directory view?
<img width="723" alt="Screen Shot 2022-02-23 at 13 18 06" src="https://user-images.githubusercontent.com/50749920/155410195-c29265c3-7513-4ec5-98ea-0963fc1f0127.png">

**Comment by JulianHayward** [comment]
getting the suggested and other 'good to know' AAD details will require more permissions. Closing for now but adding to backlog
