### ISSUE TITLE
Missed step 

### ISSUE THREAD

**Issue by wayneme75** [JulianHayward/Azure-MG-Sub-Governance-Reporting#85]
There is a missed step in the step by step guide:

After you create the app registration, there is a need to give it the reader rights before moving to the config in ADO, else when you create the connection in ADO and click verify it fails./

https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/setup.md#azure-portal

**Comment by JulianHayward** [comment]
PR #86 
thx
