### ISSUE TITLE
Long file names of csvs

### ISSUE THREAD

**Issue by wayneme75** [JulianHayward/Azure-MG-Sub-Governance-Reporting#88]
I have come across a number of instances where the long file names are causing issues with customers when trying to share the repo in a zip - this is most acutely affected in Windows machines.
Is there a way that we can possibly shorten the name, possibly only using the first 6-9 characters of the tenant id?

**Comment by JulianHayward** [comment]
@wayneme75 the problem on windows systems is the folder depth and file name length of the JSON files (folder structure reflecting the MG structure). I fear there is not good solution to this issue. Zipping only the CSV outputs is possible. Please close if you are super happy with the answer :)
