### ISSUE TITLE
Potential security issue - information disclosure

### ISSUE THREAD

**Issue by bubbletroubles** [JulianHayward/Azure-MG-Sub-Governance-Reporting#91]
Thanks for developing such a great tool, its very powerful. I may have found a potential information disclosure vulnerability with AzGovViz when run on Azure DevOps pipelines in the method documented.

Take the scenario below
- AzGovViz is run in Azure DevOps pipelines (as documented [here](https://github.com/microsoft/CloudAdoptionFramework/blob/master/govern/AzureGovernanceVisualizer/setup.md) )
- The Azure DevOps project has the setting "Limit job authorization scope to current project for non-release pipelines" off (required for cross-project access from build agents)
- The AzGovViz repo has write access granted to DevOps build agents as documented [here](https://github.com/microsoft/CloudAdoptionFramework/blob/master/govern/AzureGovernanceVisualizer/setup.md#grant-permissions-on-azgovviz-azdo-repository) and [here](https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/main/README.md#azure-devops)

In the scenario above, anyone with access to run a job on a build agent within the entire DevOps org (any Project) as the ability to **overwrite** the AzGovViz script with a script of their choosing. As this runs with high level tenant reader rights, it could lead to unintended information disclosure.

There is a warning on the [DevOps doco](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml) about this, however its obscure (e.g. a sys admin may setup AzGovViz not knowing that this setting is enabled in DevOps which gives essentially high level reader rights in the tenant to anyone who can access a build agent).

There could be a couple of solutions here
- to have the script in one repo (which is read-only to DevOps build agents) and the output in another repo (which is writable by DevOps build agents). This protects the integrity of the script. However a note that anyone who can run a build can still view the contents of the "output" repo. 
- Update the AzGovViz install steps to reference this setting and warn of the impact, and to use the multi-repo model for script protection.

**Comment by JulianHayward** [comment]
thanks for drawing the scenario in detail. So, you have set the "Limit job authorization scope to current project for non-release pipelines" to 'disabled' because you have the need for cross project access (whilst the default setting would be 'enabled') - why not enable the setting on the AzGovViz project? I am free to have a chat offline, just contact me on LinkedIn.

**Comment by bubbletroubles** [comment]
I'll reach out on LinkedIn to chat. Add to why not set it at the  AzGovViz project scope, our DevOps Project standard is to have one Project per business area (not per application or product). Other pipelines in the Project need the job scope seeing turned off to access a common "Automation Library" in another Project.

**Comment by JulianHayward** [comment]
taken offline
