### ISSUE TITLE
Request: Timestamp on the HTML output

### ISSUE THREAD

**Issue by wayneme75** [JulianHayward/Azure-MG-Sub-Governance-Reporting#98]
Can we add a last updated / refreshed time stamp on the HTML output.

**Comment by JulianHayward** [comment]
do you mean the file name or inner the html?

inner html mouseOver on the question mark (top left)
<img width="420" alt="image" src="https://user-images.githubusercontent.com/45695032/168015608-1a7b01a0-7438-45f9-92d5-54289cea167f.png">

**Comment by wayneme75** [comment]
I see that now, it wasn’t obvious. The mouse over takes 3-5 seconds to come up.
I was thinking just the date when it was last refreshed..

On May 12, 2022, at 02:30, quoteee ***@***.******@***.***>> wrote:



do you mean the file name or inner the html?

inner html mouseOver on the question mark (top left)
[image]<https://user-images.githubusercontent.com/45695032/168015608-1a7b01a0-7438-45f9-92d5-54289cea167f.png>
